import React, { createContext, useState } from "react";
import { StyleSheet, Button, View, Text } from "react-native";
import { Dropdown } from 'react-native-element-dropdown';
// import AntDesign from '@expo/vector-icons/AntDesign';

export default function Location({ navigation }) {
  const [divOptValue, setDivOptValue] = useState(null);
  const [divOptIsFocus, setDivOptIsFocus] = useState(false);
  const [cityValue, setCityValue] = useState(null);
  const [cityIsFocus, setCityIsFocus] = useState(false);
  const [countyValue, setCountyValue] = useState(null);
  const [countyIsFocus, setCountyIsFocus] = useState(false);

  return (
    < View >
      <View style={styles.container}>
        <Dropdown
          style={[styles.dropdown, divOptIsFocus && { borderColor: 'blue' }]}
          placeholderStyle={styles.placeholderStyle}
          selectedTextStyle={styles.selectedTextStyle}
          inputSearchStyle={styles.inputSearchStyle}
          data={divOptData}
          maxHeight={300}
          labelField="label"
          valueField="value"
          placeholder={!divOptIsFocus ? "Select city or county" : "..."}
          value={divOptValue}
          onFocus={() => setDivOptIsFocus(true)}
          onBlur={() => setDivOptIsFocus(false)}
          onChange={item => {
            setDivOptValue(item.value);
            setDivOptIsFocus(false);
          }}
        />
      </View>
      {divOptValue === null ? <View></View>
      :<View style={styles.container}>
        {divOptValue === 'city' ?
          <Dropdown
            style={[styles.dropdown, cityIsFocus && { borderColor: 'blue' }]}
            placeholderStyle={styles.placeholderStyle}
            selectedTextStyle={styles.selectedTextStyle}
            inputSearchStyle={styles.inputSearchStyle}
            data={cityData}
            maxHeight={300}
            labelField="label"
            valueField="value"
            placeholder={!cityIsFocus ? 'Select city' : '...'}
            search
            searchPlaceholder="Search..."
            value={cityValue}
            onFocus={() => setCityIsFocus(true)}
            onBlur={() => setCityIsFocus(false)}
            onChange={item => {
              setCityValue(item.value);
              setCityIsFocus(false);
            }}
          /> :
          <Dropdown
            style={[styles.dropdown, countyIsFocus && { borderColor: 'blue' }]}
            placeholderStyle={styles.placeholderStyle}
            selectedTextStyle={styles.selectedTextStyle}
            inputSearchStyle={styles.inputSearchStyle}
            data={countyData}
            maxHeight={300}
            labelField="label"
            valueField="value"
            placeholder={!countyIsFocus ? 'Select county' : '...'}
            search
            searchPlaceholder="Search..."
            value={countyValue}
            onFocus={() => setCountyIsFocus(true)}
            onBlur={() => setCountyIsFocus(false)}
            onChange={item => {
              setCountyValue(item.value);
              setCountyIsFocus(false);
            }}
          />
        }
      </View>}
      <Button
        title="Get Recycling Laws"
        onPress={() => {
          if (divOptValue === "city") {
            const locationRequest = createContext({
              divisionType: divOptValue,
              divisionName: cityValue,
            });
          }
          else if (divOptValue === "county") {
            const locationRequest = createContext({
              divisionType: divOptValue,
              divisionName: countyValue,
            });
          }
          navigation.navigate("Info");
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    padding: 16,
  },
  dropdown: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});

const divOptData = [
  { label: 'City', value: 'city' },
  { label: 'County', value: 'county' },
];

const cityData = [
  { label: 'Aberdeen', value: 'Aberdeen' },
  { label: 'Ahoskie', value: 'Ahoskie' },
  { label: 'Alamance', value: 'Alamance' },
  { label: 'Albemarle', value: 'Albemarle' },
  { label: 'Alliance', value: 'Alliance' },
  { label: 'Andrews', value: 'Andrews' },
  { label: 'Angier', value: 'Angier' },
  { label: 'Ansonville', value: 'Ansonville' },
  { label: 'Apex', value: 'Apex' },
  { label: 'Arapahoe', value: 'Arapahoe' },
  { label: 'Archdale', value: 'Archdale' },
  { label: 'Archer Lodge', value: 'Archer Lodge' },
  { label: 'Asheboro', value: 'Asheboro' },
  { label: 'Asheville', value: 'Asheville' },
  { label: 'Askewville', value: 'Askewville' },
  { label: 'Atkinson', value: 'Atkinson' },
  { label: 'Atlantic Beach', value: 'Atlantic Beach' },
  { label: 'Aulander', value: 'Aulander' },
  { label: 'Aurora', value: 'Aurora' },
  { label: 'Autryville', value: 'Autryville' },
  { label: 'Ayden', value: 'Ayden' },
  { label: 'Badin', value: 'Badin' },
  { label: 'Bailey', value: 'Bailey' },
  { label: 'Bakersville', value: 'Bakersville' },
  { label: 'Bald Head Island', value: 'Bald Head Island' },
  { label: 'Banner Elk', value: 'Banner Elk' },
  { label: 'Bath', value: 'Bath' },
  { label: 'Bayboro', value: 'Bayboro' },
  { label: 'Bear Grass', value: 'Bear Grass' },
  { label: 'Beaufort', value: 'Beaufort' },
  { label: 'Beech Mountain', value: 'Beech Mountain' },
  { label: 'Belhaven', value: 'Belhaven' },
  { label: 'Belmont', value: 'Belmont' },
  { label: 'Belville', value: 'Belville' },
  { label: 'Belwood', value: 'Belwood' },
  { label: 'Benson', value: 'Benson' },
  { label: 'Bermuda Run', value: 'Bermuda Run' },
  { label: 'Bessemer City', value: 'Bessemer City' },
  { label: 'Bethania', value: 'Bethania' },
  { label: 'Bethel', value: 'Bethel' },
  { label: 'Beulaville', value: 'Beulaville' },
  { label: 'Biltmore Forest', value: 'Biltmore Forest' },
  { label: 'Biscoe', value: 'Biscoe' },
  { label: 'Black Creek', value: 'Black Creek' },
  { label: 'Black Mountain', value: 'Black Mountain' },
  { label: 'Bladenboro', value: 'Bladenboro' },
  { label: 'Blowing Rock', value: 'Blowing Rock' },
  { label: 'Boardman', value: 'Boardman' },
  { label: 'Bogue', value: 'Bogue' },
  { label: 'Boiling Spring Lakes', value: 'Boiling Spring Lakes' },
  { label: 'Boiling Springs', value: 'Boiling Springs' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Bolton', value: 'Bolton' },
  { label: 'Boone', value: 'Boone' },
  { label: 'Boonville', value: 'Boonville' },
  { label: 'Bostic', value: 'Bostic' },
  { label: 'Brevard', value: 'Brevard' },
  { label: 'Bridgeton', value: 'Bridgeton' },
  { label: 'Broadway', value: 'Broadway' },
  { label: 'Brookford', value: 'Brookford' },
  { label: 'Brunswick', value: 'Brunswick' },
  { label: 'Bryson City', value: 'Bryson City' },
  { label: 'Bunn', value: 'Bunn' },
  { label: 'Burgaw', value: 'Burgaw' },
  { label: 'Burlington', value: 'Burlington' },
  { label: 'Burnsville', value: 'Burnsville' },
  { label: 'Butner', value: 'Butner' },
  { label: 'Cajahs Mountain', value: 'Cajahs Mountain' },
  { label: 'Calabash', value: 'Calabash' },
  { label: 'Calypso', value: 'Calypso' },
  { label: 'Cameron', value: 'Cameron' },
  { label: 'Candor', value: 'Candor' },
  { label: 'Canton', value: 'Canton' },
  { label: 'Cape Carteret', value: 'Cape Carteret' },
  { label: 'Carolina Beach', value: 'Carolina Beach' },
  { label: 'Carolina Shores', value: 'Carolina Shores' },
  { label: 'Carrboro', value: 'Carrboro' },
  { label: 'Carthage', value: 'Carthage' },
  { label: 'Cary', value: 'Cary' },
  { label: 'Casar', value: 'Casar' },
  { label: 'Castalia', value: 'Castalia' },
  { label: 'Caswell Beach', value: 'Caswell Beach' },
  { label: 'Catawba', value: 'Catawba' },
  { label: 'Cedar Point', value: 'Cedar Point' },
  { label: 'Cedar Rock', value: 'Cedar Rock' },
  { label: 'Cerro Gordo', value: 'Cerro Gordo' },
  { label: 'Chadbourn', value: 'Chadbourn' },
  { label: 'Chapel Hill', value: 'Chapel Hill' },
  { label: 'Charlotte', value: 'Charlotte' },
  { label: 'Cherryville', value: 'Cherryville' },
  { label: 'Chimney Rock', value: 'Chimney Rock' },
  { label: 'China Grove', value: 'China Grove' },
  { label: 'Chocowinity', value: 'Chocowinity' },
  { label: 'Claremont', value: 'Claremont' },
  { label: 'Clarkton', value: 'Clarkton' },
  { label: 'Clayton', value: 'Clayton' },
  { label: 'Clemmons', value: 'Clemmons' },
  { label: 'Cleveland', value: 'Cleveland' },
  { label: 'Clinton', value: 'Clinton' },
  { label: 'Clyde', value: 'Clyde' },
  { label: 'Coats', value: 'Coats' },
  { label: 'Cofield', value: 'Cofield' },
  { label: 'Colerain', value: 'Colerain' },
  { label: 'Columbia', value: 'Columbia' },
  { label: 'Columbus', value: 'Columbus' },
  { label: 'Como', value: 'Como' },
  { label: 'Concord', value: 'Concord' },
  { label: 'Conetoe', value: 'Conetoe' },
  { label: 'Connelly Springs', value: 'Connelly Springs' },
  { label: 'Conover', value: 'Conover' },
  { label: 'Conway', value: 'Conway' },
  { label: 'Cooleemee', value: 'Cooleemee' },
  { label: 'Cornelius', value: 'Cornelius' },
  { label: 'Cove City', value: 'Cove City' },
  { label: 'Cramerton', value: 'Cramerton' },
  { label: 'Creedmoor', value: 'Creedmoor' },
  { label: 'Creswell', value: 'Creswell' },
  { label: 'Crossnore', value: 'Crossnore' },
  { label: 'Dallas', value: 'Dallas' },
  { label: 'Danbury', value: 'Danbury' },
  { label: 'Davidson', value: 'Davidson' },
  { label: 'Denton', value: 'Denton' },
  { label: 'Dillsboro', value: 'Dillsboro' },
  { label: 'Dobbins Heights', value: 'Dobbins Heights' },
  { label: 'Dobson', value: 'Dobson' },
  { label: 'Dortches', value: 'Dortches' },
  { label: 'Dover', value: 'Dover' },
  { label: 'Drexel', value: 'Drexel' },
  { label: 'Dublin', value: 'Dublin' },
  { label: 'Duck', value: 'Duck' },
  { label: 'Dunn', value: 'Dunn' },
  { label: 'Durham', value: 'Durham' },
  { label: 'Earl', value: 'Earl' },
  { label: 'East Arcadia', value: 'East Arcadia' },
  { label: 'East Bend', value: 'East Bend' },
  { label: 'East Spencer', value: 'East Spencer' },
  { label: 'Eastover', value: 'Eastover' },
  { label: 'Eden', value: 'Eden' },
  { label: 'Edenton', value: 'Edenton' },
  { label: 'Elizabeth City', value: 'Elizabeth City' },
  { label: 'Elizabethtown', value: 'Elizabethtown' },
  { label: 'Elk Park', value: 'Elk Park' },
  { label: 'Elkin', value: 'Elkin' },
  { label: 'Ellenboro', value: 'Ellenboro' },
  { label: 'Ellerbe', value: 'Ellerbe' },
  { label: 'Elm City', value: 'Elm City' },
  { label: 'Elon', value: 'Elon' },
  { label: 'Emerald Isle', value: 'Emerald Isle' },
  { label: 'Enfield', value: 'Enfield' },
  { label: 'Erwin', value: 'Erwin' },
  { label: 'Eureka', value: 'Eureka' },
  { label: 'Everetts', value: 'Everetts' },
  { label: 'Fair Bluff', value: 'Fair Bluff' },
  { label: 'Fairmont', value: 'Fairmont' },
  { label: 'Fairview', value: 'Fairview' },
  { label: 'Faison', value: 'Faison' },
  { label: 'Faith', value: 'Faith' },
  { label: 'Falcon', value: 'Falcon' },
  { label: 'Falkland', value: 'Falkland' },
  { label: 'Fallston', value: 'Fallston' },
  { label: 'Farmville', value: 'Farmville' },
  { label: 'Fayetteville', value: 'Fayetteville' },
  { label: 'Flat Rock', value: 'Flat Rock' },
  { label: 'Fletcher', value: 'Fletcher' },
  { label: 'Fontana Dam', value: 'Fontana Dam' },
  { label: 'Forest City', value: 'Forest City' },
  { label: 'Forest Hills', value: 'Forest Hills' },
  { label: 'Fountain', value: 'Fountain' },
  { label: 'Four Oaks', value: 'Four Oaks' },
  { label: 'Foxfire Village', value: 'Foxfire Village' },
  { label: 'Franklin', value: 'Franklin' },
  { label: 'Franklinton', value: 'Franklinton' },
  { label: 'Franklinville', value: 'Franklinville' },
  { label: 'Fremont', value: 'Fremont' },
  { label: 'Fuquay-Varina', value: 'Fuquay-Varina' },
  { label: 'Gamewell', value: 'Gamewell' },
  { label: 'Garland', value: 'Garland' },
  { label: 'Garner', value: 'Garner' },
  { label: 'Garysburg', value: 'Garysburg' },
  { label: 'Gaston', value: 'Gaston' },
  { label: 'Gastonia', value: 'Gastonia' },
  { label: 'Gatesville', value: 'Gatesville' },
  { label: 'Gibson', value: 'Gibson' },
  { label: 'Gibsonville', value: 'Gibsonville' },
  { label: 'Glen Alpine', value: 'Glen Alpine' },
  { label: 'Godwin', value: 'Godwin' },
  { label: 'Goldsboro', value: 'Goldsboro' },
  { label: 'Goldston', value: 'Goldston' },
  { label: 'Graham', value: 'Graham' },
  { label: 'Grandfather Village', value: 'Grandfather Village' },
  { label: 'Granite Falls', value: 'Granite Falls' },
  { label: 'Granite Quarry', value: 'Granite Quarry' },
  { label: 'Grantsboro', value: 'Grantsboro' },
  { label: 'Green Level', value: 'Green Level' },
  { label: 'Greenevers', value: 'Greenevers' },
  { label: 'Greensboro', value: 'Greensboro' },
  { label: 'Greenville', value: 'Greenville' },
  { label: 'Grifton', value: 'Grifton' },
  { label: 'Grimesland', value: 'Grimesland' },
  { label: 'Grover', value: 'Grover' },
  { label: 'Halifax', value: 'Halifax' },
  { label: 'Hamilton', value: 'Hamilton' },
  { label: 'Hamlet', value: 'Hamlet' },
  { label: 'Harmony', value: 'Harmony' },
  { label: 'Harrells', value: 'Harrells' },
  { label: 'Harrellsville', value: 'Harrellsville' },
  { label: 'Harrisburg', value: 'Harrisburg' },
  { label: 'Hassell', value: 'Hassell' },
  { label: 'Havelock', value: 'Havelock' },
  { label: 'Haw River', value: 'Haw River' },
  { label: 'Hayesville', value: 'Hayesville' },
  { label: 'Hemby Bridge', value: 'Hemby Bridge' },
  { label: 'Henderson', value: 'Henderson' },
  { label: 'Hendersonville', value: 'Hendersonville' },
  { label: 'Hertford', value: 'Hertford' },
  { label: 'Hickory', value: 'Hickory' },
  { label: 'High Point', value: 'High Point' },
  { label: 'High Shoals', value: 'High Shoals' },
  { label: 'Highlands', value: 'Highlands' },
  { label: 'Hildebran', value: 'Hildebran' },
  { label: 'Hillsborough', value: 'Hillsborough' },
  { label: 'Hobgood', value: 'Hobgood' },
  { label: 'Hoffman', value: 'Hoffman' },
  { label: 'Holden Beach', value: 'Holden Beach' },
  { label: 'Holly Ridge', value: 'Holly Ridge' },
  { label: 'Holly Springs', value: 'Holly Springs' },
  { label: 'Hookerton', value: 'Hookerton' },
  { label: 'Hope Mills', value: 'Hope Mills' },
  { label: 'Hot Springs', value: 'Hot Springs' },
  { label: 'Hudson', value: 'Hudson' },
  { label: 'Huntersville', value: 'Huntersville' },
  { label: 'Indian Beach', value: 'Indian Beach' },
  { label: 'Indian Trail', value: 'Indian Trail' },
  { label: 'Jackson', value: 'Jackson' },
  { label: 'Jacksonville', value: 'Jacksonville' },
  { label: 'Jamestown', value: 'Jamestown' },
  { label: 'Jamesville', value: 'Jamesville' },
  { label: 'Jefferson', value: 'Jefferson' },
  { label: 'Jonesville', value: 'Jonesville' },
  { label: 'Kannapolis', value: 'Kannapolis' },
  { label: 'Kelford', value: 'Kelford' },
  { label: 'Kenansville', value: 'Kenansville' },
  { label: 'Kenly', value: 'Kenly' },
  { label: 'Kernersville', value: 'Kernersville' },
  { label: 'Kill Devil Hills', value: 'Kill Devil Hills' },
  { label: 'King', value: 'King' },
  { label: 'Kings Mountain', value: 'Kings Mountain' },
  { label: 'Kingstown', value: 'Kingstown' },
  { label: 'Kinston', value: 'Kinston' },
  { label: 'Kittrell', value: 'Kittrell' },
  { label: 'Kitty Hawk', value: 'Kitty Hawk' },
  { label: 'Knightdale', value: 'Knightdale' },
  { label: 'Kure Beach', value: 'Kure Beach' },
  { label: 'La Grange', value: 'La Grange' },
  { label: 'Lake Lure', value: 'Lake Lure' },
  { label: 'Lake Park', value: 'Lake Park' },
  { label: 'Lake Santeetlah', value: 'Lake Santeetlah' },
  { label: 'Lake Waccamaw', value: 'Lake Waccamaw' },
  { label: 'Landis', value: 'Landis' },
  { label: 'Lansing', value: 'Lansing' },
  { label: 'Lasker', value: 'Lasker' },
  { label: 'Lattimore', value: 'Lattimore' },
  { label: 'Laurel Park', value: 'Laurel Park' },
  { label: 'Laurinburg', value: 'Laurinburg' },
  { label: 'Lawndale', value: 'Lawndale' },
  { label: 'Leggett', value: 'Leggett' },
  { label: 'Leland', value: 'Leland' },
  { label: 'Lenoir', value: 'Lenoir' },
  { label: 'Lewiston Woodville', value: 'Lewiston Woodville' },
  { label: 'Lewisville', value: 'Lewisville' },
  { label: 'Lexington', value: 'Lexington' },
  { label: 'Liberty', value: 'Liberty' },
  { label: 'Lilesville', value: 'Lilesville' },
  { label: 'Lillington', value: 'Lillington' },
  { label: 'Lincolnton', value: 'Lincolnton' },
  { label: 'Linden', value: 'Linden' },
  { label: 'Littleton', value: 'Littleton' },
  { label: 'Locust', value: 'Locust' },
  { label: 'Long View', value: 'Long View' },
  { label: 'Louisburg', value: 'Louisburg' },
  { label: 'Love Valley', value: 'Love Valley' },
  { label: 'Lowell', value: 'Lowell' },
  { label: 'Lucama', value: 'Lucama' },
  { label: 'Lumber Bridge', value: 'Lumber Bridge' },
  { label: 'Lumberton', value: 'Lumberton' },
  { label: 'Macclesfield', value: 'Macclesfield' },
  { label: 'Macon', value: 'Macon' },
  { label: 'Madison', value: 'Madison' },
  { label: 'Maggie Valley', value: 'Maggie Valley' },
  { label: 'Magnolia', value: 'Magnolia' },
  { label: 'Maiden', value: 'Maiden' },
  { label: 'Manteo', value: 'Manteo' },
  { label: 'Marietta', value: 'Marietta' },
  { label: 'Marion', value: 'Marion' },
  { label: 'Mars Hill', value: 'Mars Hill' },
  { label: 'Marshall', value: 'Marshall' },
  { label: 'Marshville', value: 'Marshville' },
  { label: 'Marvin', value: 'Marvin' },
  { label: 'Matthews', value: 'Matthews' },
  { label: 'Maxton', value: 'Maxton' },
  { label: 'Mayodan', value: 'Mayodan' },
  { label: 'Maysville', value: 'Maysville' },
  { label: 'McAdenville', value: 'McAdenville' },
  { label: 'McDonald', value: 'McDonald' },
  { label: 'McFarlan', value: 'McFarlan' },
  { label: 'Mebane', value: 'Mebane' },
  { label: 'Mesic', value: 'Mesic' },
  { label: 'Micro', value: 'Micro' },
  { label: 'Middleburg', value: 'Middleburg' },
  { label: 'Middlesex', value: 'Middlesex' },
  { label: 'Midland', value: 'Midland' },
  { label: 'Midway', value: 'Midway' },
  { label: 'Mills River', value: 'Mills River' },
  { label: 'Milton', value: 'Milton' },
  { label: 'Mineral Springs', value: 'Mineral Springs' },
  { label: 'Minnesott Beach', value: 'Minnesott Beach' },
  { label: 'Mint Hill', value: 'Mint Hill' },
  { label: 'Misenheimer', value: 'Misenheimer' },
  { label: 'Mocksville', value: 'Mocksville' },
  { label: 'Momeyer', value: 'Momeyer' },
  { label: 'Monroe', value: 'Monroe' },
  { label: 'Montreat', value: 'Montreat' },
  { label: 'Mooresboro', value: 'Mooresboro' },
  { label: 'Mooresville', value: 'Mooresville' },
  { label: 'Morehead City', value: 'Morehead City' },
  { label: 'Morganton', value: 'Morganton' },
  { label: 'Morrisville', value: 'Morrisville' },
  { label: 'Morven', value: 'Morven' },
  { label: 'Mount Airy', value: 'Mount Airy' },
  { label: 'Mount Gilead', value: 'Mount Gilead' },
  { label: 'Mount Holly', value: 'Mount Holly' },
  { label: 'Mount Olive', value: 'Mount Olive' },
  { label: 'Mount Pleasant', value: 'Mount Pleasant' },
  { label: 'Murfreesboro', value: 'Murfreesboro' },
  { label: 'Murphy', value: 'Murphy' },
  { label: 'Nags Head', value: 'Nags Head' },
  { label: 'Nashville', value: 'Nashville' },
  { label: 'Navassa', value: 'Navassa' },
  { label: 'New Bern', value: 'New Bern' },
  { label: 'New London', value: 'New London' },
  { label: 'Newland', value: 'Newland' },
  { label: 'Newport', value: 'Newport' },
  { label: 'Newton', value: 'Newton' },
  { label: 'Newton Grove', value: 'Newton Grove' },
  { label: 'Norlina', value: 'Norlina' },
  { label: 'Norman', value: 'Norman' },
  { label: 'North Topsail Beach', value: 'North Topsail Beach' },
  { label: 'North Wilkesboro', value: 'North Wilkesboro' },
  { label: 'Northwest', value: 'Northwest' },
  { label: 'Norwood', value: 'Norwood' },
  { label: 'Oak City', value: 'Oak City' },
  { label: 'Oak Island', value: 'Oak Island' },
  { label: 'Oak Ridge', value: 'Oak Ridge' },
  { label: 'Oakboro', value: 'Oakboro' },
  { label: 'Ocean Isle Beach', value: 'Ocean Isle Beach' },
  { label: 'Old Fort', value: 'Old Fort' },
  { label: 'Oriental', value: 'Oriental' },
  { label: 'Orrum', value: 'Orrum' },
  { label: 'Ossipee', value: 'Ossipee' },
  { label: 'Oxford', value: 'Oxford' },
  { label: 'Pantego', value: 'Pantego' },
  { label: 'Parkton', value: 'Parkton' },
  { label: 'Parmele', value: 'Parmele' },
  { label: 'Patterson Springs', value: 'Patterson Springs' },
  { label: 'Peachland', value: 'Peachland' },
  { label: 'Peletier', value: 'Peletier' },
  { label: 'Pembroke', value: 'Pembroke' },
  { label: 'Pikeville', value: 'Pikeville' },
  { label: 'Pilot Mountain', value: 'Pilot Mountain' },
  { label: 'Pine Knoll Shores', value: 'Pine Knoll Shores' },
  { label: 'Pine Level', value: 'Pine Level' },
  { label: 'Pinebluff', value: 'Pinebluff' },
  { label: 'Pinehurst', value: 'Pinehurst' },
  { label: 'Pinetops', value: 'Pinetops' },
  { label: 'Pineville', value: 'Pineville' },
  { label: 'Pink Hill', value: 'Pink Hill' },
  { label: 'Pittsboro', value: 'Pittsboro' },
  { label: 'Pleasant Garden', value: 'Pleasant Garden' },
  { label: 'Plymouth', value: 'Plymouth' },
  { label: 'Polkton', value: 'Polkton' },
  { label: 'Polkville', value: 'Polkville' },
  { label: 'Pollocksville', value: 'Pollocksville' },
  { label: 'Powellsville', value: 'Powellsville' },
  { label: 'Princeton', value: 'Princeton' },
  { label: 'Princeville', value: 'Princeville' },
  { label: 'Proctorville', value: 'Proctorville' },
  { label: 'Raeford', value: 'Raeford' },
  { label: 'Raleigh', value: 'Raleigh' },
  { label: 'Ramseur', value: 'Ramseur' },
  { label: 'Randleman', value: 'Randleman' },
  { label: 'Ranlo', value: 'Ranlo' },
  { label: 'Raynham', value: 'Raynham' },
  { label: 'Red Cross', value: 'Red Cross' },
  { label: 'Red Oak', value: 'Red Oak' },
  { label: 'Red Springs', value: 'Red Springs' },
  { label: 'Reidsville', value: 'Reidsville' },
  { label: 'Rennert', value: 'Rennert' },
  { label: 'Rhodhiss', value: 'Rhodhiss' },
  { label: 'Rich Square', value: 'Rich Square' },
  { label: 'Richfield', value: 'Richfield' },
  { label: 'Richlands', value: 'Richlands' },
  { label: 'River Bend', value: 'River Bend' },
  { label: 'Roanoke Rapids', value: 'Roanoke Rapids' },
  { label: 'Robbins', value: 'Robbins' },
  { label: 'Robbinsville', value: 'Robbinsville' },
  { label: 'Robersonville', value: 'Robersonville' },
  { label: 'Rockingham', value: 'Rockingham' },
  { label: 'Rockwell', value: 'Rockwell' },
  { label: 'Rocky Mount', value: 'Rocky Mount' },
  { label: 'Rolesville', value: 'Rolesville' },
  { label: 'Ronda', value: 'Ronda' },
  { label: 'Roper', value: 'Roper' },
  { label: 'Rose Hill', value: 'Rose Hill' },
  { label: 'Roseboro', value: 'Roseboro' },
  { label: 'Rosman', value: 'Rosman' },
  { label: 'Rowland', value: 'Rowland' },
  { label: 'Roxboro', value: 'Roxboro' },
  { label: 'Roxobel', value: 'Roxobel' },
  { label: 'Rural Hall', value: 'Rural Hall' },
  { label: 'Ruth', value: 'Ruth' },
  { label: 'Rutherford College', value: 'Rutherford College' },
  { label: 'Rutherfordton', value: 'Rutherfordton' },
  { label: 'Saint Helena', value: 'Saint Helena' },
  { label: 'Saint James', value: 'Saint James' },
  { label: 'Saint Pauls', value: 'Saint Pauls' },
  { label: 'Salemburg', value: 'Salemburg' },
  { label: 'Salisbury', value: 'Salisbury' },
  { label: 'Saluda', value: 'Saluda' },
  { label: 'Sandy Creek', value: 'Sandy Creek' },
  { label: 'Sandyfield', value: 'Sandyfield' },
  { label: 'Sanford', value: 'Sanford' },
  { label: 'Saratoga', value: 'Saratoga' },
  { label: 'Sawmills', value: 'Sawmills' },
  { label: 'Scotland Neck', value: 'Scotland Neck' },
  { label: 'Seaboard', value: 'Seaboard' },
  { label: 'Seagrove', value: 'Seagrove' },
  { label: 'Sedalia', value: 'Sedalia' },
  { label: 'Selma', value: 'Selma' },
  { label: 'Seven Devils', value: 'Seven Devils' },
  { label: 'Seven Springs', value: 'Seven Springs' },
  { label: 'Severn', value: 'Severn' },
  { label: 'Shallotte', value: 'Shallotte' },
  { label: 'Sharpsburg', value: 'Sharpsburg' },
  { label: 'Shelby', value: 'Shelby' },
  { label: 'Siler City', value: 'Siler City' },
  { label: 'Simpson', value: 'Simpson' },
  { label: 'Sims', value: 'Sims' },
  { label: 'Smithfield', value: 'Smithfield' },
  { label: 'Snow Hill', value: 'Snow Hill' },
  { label: 'Southern Pines', value: 'Southern Pines' },
  { label: 'Southern Shores', value: 'Southern Shores' },
  { label: 'Southport', value: 'Southport' },
  { label: 'Sparta', value: 'Sparta' },
  { label: 'Speed', value: 'Speed' },
  { label: 'Spencer', value: 'Spencer' },
  { label: 'Spencer Mountain', value: 'Spencer Mountain' },
  { label: 'Spindale', value: 'Spindale' },
  { label: 'Spring Hope', value: 'Spring Hope' },
  { label: 'Spring Lake', value: 'Spring Lake' },
  { label: 'Spruce Pine', value: 'Spruce Pine' },
  { label: 'Staley', value: 'Staley' },
  { label: 'Stallings', value: 'Stallings' },
  { label: 'Stanfield', value: 'Stanfield' },
  { label: 'Stanley', value: 'Stanley' },
  { label: 'Stantonsburg', value: 'Stantonsburg' },
  { label: 'Star', value: 'Star' },
  { label: 'Statesville', value: 'Statesville' },
  { label: 'Stedman', value: 'Stedman' },
  { label: 'Stem', value: 'Stem' },
  { label: 'Stokesdale', value: 'Stokesdale' },
  { label: 'Stoneville', value: 'Stoneville' },
  { label: 'Stonewall', value: 'Stonewall' },
  { label: 'Stovall', value: 'Stovall' },
  { label: 'Sugar Mountain', value: 'Sugar Mountain' },
  { label: 'Summerfield', value: 'Summerfield' },
  { label: 'Sunset Beach', value: 'Sunset Beach' },
  { label: 'Surf City', value: 'Surf City' },
  { label: 'Swansboro', value: 'Swansboro' },
  { label: 'Swepsonville', value: 'Swepsonville' },
  { label: 'Sylva', value: 'Sylva' },
  { label: 'Tabor City', value: 'Tabor City' },
  { label: 'Tar Heel', value: 'Tar Heel' },
  { label: 'Tarboro', value: 'Tarboro' },
  { label: 'Taylorsville', value: 'Taylorsville' },
  { label: 'Taylortown', value: 'Taylortown' },
  { label: 'Teachey', value: 'Teachey' },
  { label: 'Thomasville', value: 'Thomasville' },
  { label: 'Tobaccoville', value: 'Tobaccoville' },
  { label: 'Topsail Beach', value: 'Topsail Beach' },
  { label: 'Trent Woods', value: 'Trent Woods' },
  { label: 'Trenton', value: 'Trenton' },
  { label: 'Trinity', value: 'Trinity' },
  { label: 'Troutman', value: 'Troutman' },
  { label: 'Troy', value: 'Troy' },
  { label: 'Tryon', value: 'Tryon' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Unionville', value: 'Unionville' },
  { label: 'Valdese', value: 'Valdese' },
  { label: 'Vanceboro', value: 'Vanceboro' },
  { label: 'Vandemere', value: 'Vandemere' },
  { label: 'Varnamtown', value: 'Varnamtown' },
  { label: 'Vass', value: 'Vass' },
  { label: 'Waco', value: 'Waco' },
  { label: 'Wade', value: 'Wade' },
  { label: 'Wadesboro', value: 'Wadesboro' },
  { label: 'Wagram', value: 'Wagram' },
  { label: 'Wake Forest', value: 'Wake Forest' },
  { label: 'Walkertown', value: 'Walkertown' },
  { label: 'Wallace', value: 'Wallace' },
  { label: 'Wallburg', value: 'Wallburg' },
  { label: 'Walnut Cove', value: 'Walnut Cove' },
  { label: 'Walnut Creek', value: 'Walnut Creek' },
  { label: 'Walstonburg', value: 'Walstonburg' },
  { label: 'Warrenton', value: 'Warrenton' },
  { label: 'Warsaw', value: 'Warsaw' },
  { label: 'Washington', value: 'Washington' },
  { label: 'Washington Park', value: 'Washington Park' },
  { label: 'Watha', value: 'Watha' },
  { label: 'Waxhaw', value: 'Waxhaw' },
  { label: 'Waynesville', value: 'Waynesville' },
  { label: 'Weaverville', value: 'Weaverville' },
  { label: 'Webster', value: 'Webster' },
  { label: 'Weddington', value: 'Weddington' },
  { label: 'Weldon', value: 'Weldon' },
  { label: 'Wendell', value: 'Wendell' },
  { label: 'Wentworth', value: 'Wentworth' },
  { label: 'Wesley Chapel', value: 'Wesley Chapel' },
  { label: 'West Jefferson', value: 'West Jefferson' },
  { label: 'Whispering Pines', value: 'Whispering Pines' },
  { label: 'Whitakers', value: 'Whitakers' },
  { label: 'White Lake', value: 'White Lake' },
  { label: 'Whiteville', value: 'Whiteville' },
  { label: 'Whitsett', value: 'Whitsett' },
  { label: 'Wilkesboro', value: 'Wilkesboro' },
  { label: 'Williamston', value: 'Williamston' },
  { label: 'Wilmington', value: 'Wilmington' },
  { label: 'Wilson', value: 'Wilson' },
  { label: 'Wilsons Mills', value: 'Wilsons Mills' },
  { label: 'Windsor', value: 'Windsor' },
  { label: 'Winfall', value: 'Winfall' },
  { label: 'Wingate', value: 'Wingate' },
  { label: 'Winston-Salem', value: 'Winston-Salem' },
  { label: 'Winterville', value: 'Winterville' },
  { label: 'Winton', value: 'Winton' },
  { label: 'Woodfin', value: 'Woodfin' },
  { label: 'Woodland', value: 'Woodland' },
  { label: 'Wrightsville Beach', value: 'Wrightsville Beach' },
  { label: 'Yadkinville', value: 'Yadkinville' },
  { label: 'Yanceyville', value: 'Yanceyville' },
  { label: 'Youngsville', value: 'Youngsville' },
  { label: 'Zebulon', value: 'Zebulon' },
];

const countyData = [
  { label: 'Alamance', value: 'ALAMANCE' },
  { label: 'Alexander', value: 'ALEXANDER' },
  { label: 'Alleghany', value: 'ALLEGHANY' },
  { label: 'Anson', value: 'ANSON' },
  { label: 'Ashe', value: 'ASHE' },
  { label: 'Avery', value: 'AVERY' },
  { label: 'Beaufort', value: 'BEAUFORT' },
  { label: 'Bertie', value: 'BERTIE' },
  { label: 'Bladen', value: 'BLADEN' },
  { label: 'Brunswick', value: 'BRUNSWICK' },
  { label: 'Buncombe', value: 'BUNCOMBE' },
  { label: 'Burke', value: 'BURKE' },
  { label: 'Cabarrus', value: 'CABARRUS' },
  { label: 'Caldwell', value: 'CALDWELL' },
  { label: 'Camden', value: 'CAMDEN' },
  { label: 'Carteret', value: 'CARTERET' },
  { label: 'Caswell', value: 'CASWELL' },
  { label: 'Catawba', value: 'CATAWBA' },
  { label: 'Chatham', value: 'CHATHAM' },
  { label: 'Cherokee', value: 'CHEROKEE' },
  { label: 'Chowan', value: 'CHOWAN' },
  { label: 'Clay', value: 'CLAY' },
  { label: 'Cleveland', value: 'CLEVELAND' },
  { label: 'Columbus', value: 'COLUMBUS' },
  { label: 'Craven', value: 'CRAVEN' },
  { label: 'Cumberland', value: 'CUMBERLAND' },
  { label: 'Currituck', value: 'CURRITUCK' },
  { label: 'Dare', value: 'DARE' },
  { label: 'Davidson', value: 'DAVIDSON' },
  { label: 'Davie', value: 'DAVIE' },
  { label: 'Duplin', value: 'DUPLIN' },
  { label: 'Durham', value: 'DURHAM' },
  { label: 'Edgecombe', value: 'EDGECOMBE' },
  { label: 'Forsyth', value: 'FORSYTH' },
  { label: 'Franklin', value: 'FRANKLIN' },
  { label: 'Gaston', value: 'GASTON' },
  { label: 'Gates', value: 'GATES' },
  { label: 'Graham', value: 'GRAHAM' },
  { label: 'Granville', value: 'GRANVILLE' },
  { label: 'Greene', value: 'GREENE' },
  { label: 'Guilford', value: 'GUILFORD' },
  { label: 'Halifax', value: 'HALIFAX' },
  { label: 'Harnett', value: 'HARNETT' },
  { label: 'Haywood', value: 'HAYWOOD' },
  { label: 'Henderson', value: 'HENDERSON' },
  { label: 'Hertford', value: 'HERTFORD' },
  { label: 'Hoke', value: 'HOKE' },
  { label: 'Hyde', value: 'HYDE' },
  { label: 'Iredell', value: 'IREDELL' },
  { label: 'Jackson', value: 'JACKSON' },
  { label: 'Johnston', value: 'JOHNSTON' },
  { label: 'Jones', value: 'JONES' },
  { label: 'Lee', value: 'LEE' },
  { label: 'Lenoir', value: 'LENOIR' },
  { label: 'Lincoln', value: 'LINCOLN' },
  { label: 'Macon', value: 'MACON' },
  { label: 'Madison', value: 'MADISON' },
  { label: 'Martin', value: 'MARTIN' },
  { label: 'Mcdowell', value: 'MCDOWELL' },
  { label: 'Mecklenburg', value: 'MECKLENBURG' },
  { label: 'Mitchell', value: 'MITCHELL' },
  { label: 'Montgomery', value: 'MONTGOMERY' },
  { label: 'Moore', value: 'MOORE' },
  { label: 'Nash', value: 'NASH' },
  { label: 'New hanover', value: 'NEW HANOVER' },
  { label: 'Northampton', value: 'NORTHAMPTON' },
  { label: 'Onslow', value: 'ONSLOW' },
  { label: 'Orange', value: 'ORANGE' },
  { label: 'Pamlico', value: 'PAMLICO' },
  { label: 'Pasquotank', value: 'PASQUOTANK' },
  { label: 'Pender', value: 'PENDER' },
  { label: 'Perquimans', value: 'PERQUIMANS' },
  { label: 'Person', value: 'PERSON' },
  { label: 'Pitt', value: 'PITT' },
  { label: 'Polk', value: 'POLK' },
  { label: 'Randolph', value: 'RANDOLPH' },
  { label: 'Richmond', value: 'RICHMOND' },
  { label: 'Robeson', value: 'ROBESON' },
  { label: 'Rockingham', value: 'ROCKINGHAM' },
  { label: 'Rowan', value: 'ROWAN' },
  { label: 'Rutherford', value: 'RUTHERFORD' },
  { label: 'Sampson', value: 'SAMPSON' },
  { label: 'Scotland', value: 'SCOTLAND' },
  { label: 'Stanly', value: 'STANLY' },
  { label: 'Stokes', value: 'STOKES' },
  { label: 'Surry', value: 'SURRY' },
  { label: 'Swain', value: 'SWAIN' },
  { label: 'Transylvania', value: 'TRANSYLVANIA' },
  { label: 'Tyrrell', value: 'TYRRELL' },
  { label: 'Union', value: 'UNION' },
  { label: 'Vance', value: 'VANCE' },
  { label: 'Wake', value: 'WAKE' },
  { label: 'Warren', value: 'WARREN' },
  { label: 'Washington', value: 'WASHINGTON' },
  { label: 'Watauga', value: 'WATAUGA' },
  { label: 'Wayne', value: 'WAYNE' },
  { label: 'Wilkes', value: 'WILKES' },
  { label: 'Wilson', value: 'WILSON' },
  { label: 'Yadkin', value: 'YADKIN' },
  { label: 'Yancey', value: 'YANCEY' },
];