import React, { useState } from "react";
import { StyleSheet, Button, View, Text } from "react-native";
import { Dropdown } from 'react-native-element-dropdown';
// import AntDesign from '@expo/vector-icons/AntDesign';

const divOptsData = [
  { label: 'City', value: '1' },
  { label: 'County', value: '2' },
];

const cityData = [
  { label: 'Aberdeen', value: '0' },
  { label: 'Ahoskie', value: '1' },
  { label: 'Alamance', value: '2' },
  { label: 'Albemarle', value: '3' },
  { label: 'Alliance', value: '4' },
  { label: 'Andrews', value: '5' },
  { label: 'Angier', value: '6' },
  { label: 'Ansonville', value: '7' },
  { label: 'Apex', value: '8' },
  { label: 'Arapahoe', value: '9' },
  { label: 'Archdale', value: '10' },
  { label: 'Archer lodge', value: '11' },
  { label: 'Asheboro', value: '12' },
  { label: 'Asheville', value: '13' },
  { label: 'Askewville', value: '14' },
  { label: 'Atkinson', value: '15' },
  { label: 'Atlantic beach', value: '16' },
  { label: 'Aulander', value: '17' },
  { label: 'Aurora', value: '18' },
  { label: 'Autryville', value: '19' },
  { label: 'Ayden', value: '20' },
  { label: 'Badin', value: '21' },
  { label: 'Bailey', value: '22' },
  { label: 'Bakersville', value: '23' },
  { label: 'Bald head island', value: '24' },
  { label: 'Banner elk', value: '25' },
  { label: 'Bath', value: '26' },
  { label: 'Bayboro', value: '27' },
  { label: 'Bear grass', value: '28' },
  { label: 'Beaufort', value: '29' },
  { label: 'Beech mountain', value: '30' },
  { label: 'Belhaven', value: '31' },
  { label: 'Belmont', value: '32' },
  { label: 'Belville', value: '33' },
  { label: 'Belwood', value: '34' },
  { label: 'Benson', value: '35' },
  { label: 'Bermuda run', value: '36' },
  { label: 'Bessemer city', value: '37' },
  { label: 'Bethania', value: '38' },
  { label: 'Bethel', value: '39' },
  { label: 'Beulaville', value: '40' },
  { label: 'Biltmore forest', value: '41' },
  { label: 'Biscoe', value: '42' },
  { label: 'Black creek', value: '43' },
  { label: 'Black mountain', value: '44' },
  { label: 'Bladenboro', value: '45' },
  { label: 'Blowing rock', value: '46' },
  { label: 'Boardman', value: '47' },
  { label: 'Bogue', value: '48' },
  { label: 'Boiling spring lakes', value: '49' },
  { label: 'Boiling springs', value: '50' },
  { label: 'Bolivia', value: '51' },
  { label: 'Bolton', value: '52' },
  { label: 'Boone', value: '53' },
  { label: 'Boonville', value: '54' },
  { label: 'Bostic', value: '55' },
  { label: 'Brevard', value: '56' },
  { label: 'Bridgeton', value: '57' },
  { label: 'Broadway', value: '58' },
  { label: 'Brookford', value: '59' },
  { label: 'Brunswick', value: '60' },
  { label: 'Bryson city', value: '61' },
  { label: 'Bunn', value: '62' },
  { label: 'Burgaw', value: '63' },
  { label: 'Burlington', value: '64' },
  { label: 'Burnsville', value: '65' },
  { label: 'Butner', value: '66' },
  { label: 'Cajahs mountain', value: '67' },
  { label: 'Calabash', value: '68' },
  { label: 'Calypso', value: '69' },
  { label: 'Cameron', value: '70' },
  { label: 'Candor', value: '71' },
  { label: 'Canton', value: '72' },
  { label: 'Cape carteret', value: '73' },
  { label: 'Carolina beach', value: '74' },
  { label: 'Carolina shores', value: '75' },
  { label: 'Carrboro', value: '76' },
  { label: 'Carthage', value: '77' },
  { label: 'Cary', value: '78' },
  { label: 'Casar', value: '79' },
  { label: 'Castalia', value: '80' },
  { label: 'Caswell beach', value: '81' },
  { label: 'Catawba', value: '82' },
  { label: 'Cedar point', value: '83' },
  { label: 'Cedar rock', value: '84' },
  { label: 'Cerro gordo', value: '85' },
  { label: 'Chadbourn', value: '86' },
  { label: 'Chapel hill', value: '87' },
  { label: 'Charlotte', value: '88' },
  { label: 'Cherryville', value: '89' },
  { label: 'Chimney rock', value: '90' },
  { label: 'China grove', value: '91' },
  { label: 'Chocowinity', value: '92' },
  { label: 'Claremont', value: '93' },
  { label: 'Clarkton', value: '94' },
  { label: 'Clayton', value: '95' },
  { label: 'Clemmons', value: '96' },
  { label: 'Cleveland', value: '97' },
  { label: 'Clinton', value: '98' },
  { label: 'Clyde', value: '99' },
  { label: 'Coats', value: '100' },
  { label: 'Cofield', value: '101' },
  { label: 'Colerain', value: '102' },
  { label: 'Columbia', value: '103' },
  { label: 'Columbus', value: '104' },
  { label: 'Como', value: '105' },
  { label: 'Concord', value: '106' },
  { label: 'Conetoe', value: '107' },
  { label: 'Connelly springs', value: '108' },
  { label: 'Conover', value: '109' },
  { label: 'Conway', value: '110' },
  { label: 'Cooleemee', value: '111' },
  { label: 'Cornelius', value: '112' },
  { label: 'Cove city', value: '113' },
  { label: 'Cramerton', value: '114' },
  { label: 'Creedmoor', value: '115' },
  { label: 'Creswell', value: '116' },
  { label: 'Crossnore', value: '117' },
  { label: 'Dallas', value: '118' },
  { label: 'Danbury', value: '119' },
  { label: 'Davidson', value: '120' },
  { label: 'Denton', value: '121' },
  { label: 'Dillsboro', value: '122' },
  { label: 'Dobbins heights', value: '123' },
  { label: 'Dobson', value: '124' },
  { label: 'Dortches', value: '125' },
  { label: 'Dover', value: '126' },
  { label: 'Drexel', value: '127' },
  { label: 'Dublin', value: '128' },
  { label: 'Duck', value: '129' },
  { label: 'Dunn', value: '130' },
  { label: 'Durham', value: '131' },
  { label: 'Earl', value: '132' },
  { label: 'East arcadia', value: '133' },
  { label: 'East bend', value: '134' },
  { label: 'East spencer', value: '135' },
  { label: 'Eastover', value: '136' },
  { label: 'Eden', value: '137' },
  { label: 'Edenton', value: '138' },
  { label: 'Elizabeth city', value: '139' },
  { label: 'Elizabethtown', value: '140' },
  { label: 'Elk park', value: '141' },
  { label: 'Elkin', value: '142' },
  { label: 'Ellenboro', value: '143' },
  { label: 'Ellerbe', value: '144' },
  { label: 'Elm city', value: '145' },
  { label: 'Elon', value: '146' },
  { label: 'Emerald isle', value: '147' },
  { label: 'Enfield', value: '148' },
  { label: 'Erwin', value: '149' },
  { label: 'Eureka', value: '150' },
  { label: 'Everetts', value: '151' },
  { label: 'Fair bluff', value: '152' },
  { label: 'Fairmont', value: '153' },
  { label: 'Fairview', value: '154' },
  { label: 'Faison', value: '155' },
  { label: 'Faith', value: '156' },
  { label: 'Falcon', value: '157' },
  { label: 'Falkland', value: '158' },
  { label: 'Fallston', value: '159' },
  { label: 'Farmville', value: '160' },
  { label: 'Fayetteville', value: '161' },
  { label: 'Flat rock', value: '162' },
  { label: 'Fletcher', value: '163' },
  { label: 'Fontana dam', value: '164' },
  { label: 'Forest city', value: '165' },
  { label: 'Forest hills', value: '166' },
  { label: 'Fountain', value: '167' },
  { label: 'Four oaks', value: '168' },
  { label: 'Foxfire village', value: '169' },
  { label: 'Franklin', value: '170' },
  { label: 'Franklinton', value: '171' },
  { label: 'Franklinville', value: '172' },
  { label: 'Fremont', value: '173' },
  { label: 'Fuquay-varina', value: '174' },
  { label: 'Gamewell', value: '175' },
  { label: 'Garland', value: '176' },
  { label: 'Garner', value: '177' },
  { label: 'Garysburg', value: '178' },
  { label: 'Gaston', value: '179' },
  { label: 'Gastonia', value: '180' },
  { label: 'Gatesville', value: '181' },
  { label: 'Gibson', value: '182' },
  { label: 'Gibsonville', value: '183' },
  { label: 'Glen alpine', value: '184' },
  { label: 'Godwin', value: '185' },
  { label: 'Goldsboro', value: '186' },
  { label: 'Goldston', value: '187' },
  { label: 'Graham', value: '188' },
  { label: 'Grandfather village', value: '189' },
  { label: 'Granite falls', value: '190' },
  { label: 'Granite quarry', value: '191' },
  { label: 'Grantsboro', value: '192' },
  { label: 'Green level', value: '193' },
  { label: 'Greenevers', value: '194' },
  { label: 'Greensboro', value: '195' },
  { label: 'Greenville', value: '196' },
  { label: 'Grifton', value: '197' },
  { label: 'Grimesland', value: '198' },
  { label: 'Grover', value: '199' },
  { label: 'Halifax', value: '200' },
  { label: 'Hamilton', value: '201' },
  { label: 'Hamlet', value: '202' },
  { label: 'Harmony', value: '203' },
  { label: 'Harrells', value: '204' },
  { label: 'Harrellsville', value: '205' },
  { label: 'Harrisburg', value: '206' },
  { label: 'Hassell', value: '207' },
  { label: 'Havelock', value: '208' },
  { label: 'Haw river', value: '209' },
  { label: 'Hayesville', value: '210' },
  { label: 'Hemby bridge', value: '211' },
  { label: 'Henderson', value: '212' },
  { label: 'Hendersonville', value: '213' },
  { label: 'Hertford', value: '214' },
  { label: 'Hickory', value: '215' },
  { label: 'High point', value: '216' },
  { label: 'High shoals', value: '217' },
  { label: 'Highlands', value: '218' },
  { label: 'Hildebran', value: '219' },
  { label: 'Hillsborough', value: '220' },
  { label: 'Hobgood', value: '221' },
  { label: 'Murfreesboro', value: '222' },
  { label: 'Murphy', value: '223' },
  { label: 'Nags head', value: '224' },
  { label: 'Nashville', value: '225' },
  { label: 'Navassa', value: '226' },
  { label: 'New bern', value: '227' },
  { label: 'New london', value: '228' },
  { label: 'Newland', value: '229' },
  { label: 'Newport', value: '230' },
  { label: 'Newton', value: '231' },
  { label: 'Newton grove', value: '232' },
  { label: 'Norlina', value: '233' },
  { label: 'Norman', value: '234' },
  { label: 'North topsail beach', value: '235' },
  { label: 'North wilkesboro', value: '236' },
  { label: 'Northwest', value: '237' },
  { label: 'Norwood', value: '238' },
  { label: 'Oak city', value: '239' },
  { label: 'Oak island', value: '240' },
  { label: 'Oak ridge', value: '241' },
  { label: 'Oakboro', value: '242' },
  { label: 'Ocean isle beach', value: '243' },
  { label: 'Old fort', value: '244' },
  { label: 'Oriental', value: '245' },
  { label: 'Orrum', value: '246' },
  { label: 'Ossipee', value: '247' },
  { label: 'Oxford', value: '248' },
  { label: 'Pantego', value: '249' },
  { label: 'Parkton', value: '250' },
  { label: 'Parmele', value: '251' },
  { label: 'Patterson springs', value: '252' },
  { label: 'Peachland', value: '253' },
  { label: 'Peletier', value: '254' },
  { label: 'Pembroke', value: '255' },
  { label: 'Pikeville', value: '256' },
  { label: 'Pilot mountain', value: '257' },
  { label: 'Pine knoll shores', value: '258' },
  { label: 'Pine level', value: '259' },
  { label: 'Pinebluff', value: '260' },
  { label: 'Pinehurst', value: '261' },
  { label: 'Pinetops', value: '262' },
  { label: 'Pineville', value: '263' },
  { label: 'Pink hill', value: '264' },
  { label: 'Pittsboro', value: '265' },
  { label: 'Pleasant garden', value: '266' },
  { label: 'Plymouth', value: '267' },
  { label: 'Polkton', value: '268' },
  { label: 'Polkville', value: '269' },
  { label: 'Pollocksville', value: '270' },
  { label: 'Powellsville', value: '271' },
  { label: 'Princeton', value: '272' },
  { label: 'Princeville', value: '273' },
  { label: 'Proctorville', value: '274' },
  { label: 'Raeford', value: '275' },
  { label: 'Raleigh', value: '276' },
  { label: 'Ramseur', value: '277' },
  { label: 'Randleman', value: '278' },
  { label: 'Ranlo', value: '279' },
  { label: 'Raynham', value: '280' },
  { label: 'Red cross', value: '281' },
  { label: 'Red oak', value: '282' },
  { label: 'Red springs', value: '283' },
  { label: 'Reidsville', value: '284' },
  { label: 'Rennert', value: '285' },
  { label: 'Rhodhiss', value: '286' },
  { label: 'Rich square', value: '287' },
  { label: 'Richfield', value: '288' },
  { label: 'Richlands', value: '289' },
  { label: 'River bend', value: '290' },
  { label: 'Roanoke rapids', value: '291' },
  { label: 'Robbins', value: '292' },
  { label: 'Robbinsville', value: '293' },
  { label: 'Robersonville', value: '294' },
  { label: 'Rockingham', value: '295' },
  { label: 'Rockwell', value: '296' },
  { label: 'Rocky mount', value: '297' },
  { label: 'Rolesville', value: '298' },
  { label: 'Ronda', value: '299' },
  { label: 'Roper', value: '300' },
  { label: 'Rose hill', value: '301' },
  { label: 'Roseboro', value: '302' },
  { label: 'Rosman', value: '303' },
  { label: 'Rowland', value: '304' },
  { label: 'Roxboro', value: '305' },
  { label: 'Roxobel', value: '306' },
  { label: 'Rural hall', value: '307' },
  { label: 'Ruth', value: '308' },
  { label: 'Rutherford college', value: '309' },
  { label: 'Rutherfordton', value: '310' },
  { label: 'Saint helena', value: '311' },
  { label: 'Saint james', value: '312' },
  { label: 'Saint pauls', value: '313' },
  { label: 'Salemburg', value: '314' },
  { label: 'Salisbury', value: '315' },
  { label: 'Saluda', value: '316' },
  { label: 'Sandy creek', value: '317' },
  { label: 'Sandyfield', value: '318' },
  { label: 'Sanford', value: '319' },
  { label: 'Saratoga', value: '320' },
  { label: 'Sawmills', value: '321' },
  { label: 'Scotland neck', value: '322' },
  { label: 'Seaboard', value: '323' },
  { label: 'Seagrove', value: '324' },
  { label: 'Sedalia', value: '325' },
  { label: 'Selma', value: '326' },
  { label: 'Seven devils', value: '327' },
  { label: 'Seven springs', value: '328' },
  { label: 'Severn', value: '329' },
  { label: 'Shallotte', value: '330' },
  { label: 'Sharpsburg', value: '331' },
  { label: 'Shelby', value: '332' },
  { label: 'Siler city', value: '333' },
  { label: 'Simpson', value: '334' },
  { label: 'Sims', value: '335' },
  { label: 'Smithfield', value: '336' },
  { label: 'Snow hill', value: '337' },
  { label: 'Southern pines', value: '338' },
  { label: 'Southern shores', value: '339' },
  { label: 'Southport', value: '340' },
  { label: 'Sparta', value: '341' },
  { label: 'Speed', value: '342' },
  { label: 'Spencer', value: '343' },
  { label: 'Spencer mountain', value: '344' },
  { label: 'Spindale', value: '345' },
  { label: 'Spring hope', value: '346' },
  { label: 'Spring lake', value: '347' },
  { label: 'Spruce pine', value: '348' },
  { label: 'Staley', value: '349' },
  { label: 'Stallings', value: '350' },
  { label: 'Stanfield', value: '351' },
  { label: 'Stanley', value: '352' },
  { label: 'Stantonsburg', value: '353' },
  { label: 'Star', value: '354' },
  { label: 'Statesville', value: '355' },
  { label: 'Stedman', value: '356' },
  { label: 'Stem', value: '357' },
  { label: 'Stokesdale', value: '358' },
  { label: 'Stoneville', value: '359' },
  { label: 'Stonewall', value: '360' },
  { label: 'Stovall', value: '361' },
  { label: 'Sugar mountain', value: '362' },
  { label: 'Summerfield', value: '363' },
  { label: 'Sunset beach', value: '364' },
  { label: 'Surf city', value: '365' },
  { label: 'Swansboro', value: '366' },
  { label: 'Swepsonville', value: '367' },
  { label: 'Sylva', value: '368' },
  { label: 'Tabor city', value: '369' },
  { label: 'Tar heel', value: '370' },
  { label: 'Tarboro', value: '371' },
  { label: 'Taylorsville', value: '372' },
  { label: 'Taylortown', value: '373' },
  { label: 'Teachey', value: '374' },
  { label: 'Thomasville', value: '375' },
  { label: 'Tobaccoville', value: '376' },
  { label: 'Topsail beach', value: '377' },
  { label: 'Trent woods', value: '378' },
  { label: 'Trenton', value: '379' },
  { label: 'Trinity', value: '380' },
  { label: 'Troutman', value: '381' },
  { label: 'Troy', value: '382' },
  { label: 'Tryon', value: '383' },
  { label: 'Turkey', value: '384' },
  { label: 'Unionville', value: '385' },
  { label: 'Valdese', value: '386' },
  { label: 'Vanceboro', value: '387' },
  { label: 'Vandemere', value: '388' },
  { label: 'Varnamtown', value: '389' },
  { label: 'Vass', value: '390' },
  { label: 'Waco', value: '391' },
  { label: 'Wade', value: '392' },
  { label: 'Wadesboro', value: '393' },
  { label: 'Wagram', value: '394' },
  { label: 'Wake forest', value: '395' },
  { label: 'Walkertown', value: '396' },
  { label: 'Wallace', value: '397' },
  { label: 'Wallburg', value: '398' },
  { label: 'Walnut cove', value: '399' },
  { label: 'Walnut creek', value: '400' },
  { label: 'Walstonburg', value: '401' },
  { label: 'Warrenton', value: '402' },
  { label: 'Warsaw', value: '403' },
  { label: 'Washington', value: '404' },
  { label: 'Washington park', value: '405' },
  { label: 'Watha', value: '406' },
  { label: 'Waxhaw', value: '407' },
  { label: 'Waynesville', value: '408' },
  { label: 'Weaverville', value: '409' },
  { label: 'Webster', value: '410' },
  { label: 'Weddington', value: '411' },
  { label: 'Weldon', value: '412' },
  { label: 'Wendell', value: '413' },
  { label: 'Wentworth', value: '414' },
  { label: 'Wesley chapel', value: '415' },
  { label: 'West jefferson', value: '416' },
  { label: 'Whispering pines', value: '417' },
  { label: 'Whitakers', value: '418' },
  { label: 'White lake', value: '419' },
  { label: 'Whiteville', value: '420' },
  { label: 'Whitsett', value: '421' },
  { label: 'Wilkesboro', value: '422' },
  { label: 'Williamston', value: '423' },
  { label: 'Wilmington', value: '424' },
  { label: 'Wilson', value: '425' },
  { label: 'Wilsons mills', value: '426' },
  { label: 'Windsor', value: '427' },
  { label: 'Winfall', value: '428' },
  { label: 'Wingate', value: '429' },
  { label: 'Winston-salem', value: '430' },
  { label: 'Winterville', value: '431' },
  { label: 'Winton', value: '432' },
  { label: 'Woodfin', value: '433' },
  { label: 'Woodland', value: '434' },
  { label: 'Wrightsville beach', value: '435' },
  { label: 'Yadkinville', value: '436' },
  { label: 'Yanceyville', value: '437' },
  { label: 'Youngsville', value: '438' },
  { label: 'Zebulon', value: '439' },
  { label: 'Hoffman', value: '440' },
  { label: 'Holden beach', value: '441' },
  { label: 'Holly ridge', value: '442' },
  { label: 'Holly springs', value: '443' },
  { label: 'Hookerton', value: '444' },
  { label: 'Hope mills', value: '445' },
  { label: 'Hot springs', value: '446' },
  { label: 'Hudson', value: '447' },
  { label: 'Huntersville', value: '448' },
  { label: 'Indian beach', value: '449' },
  { label: 'Indian trail', value: '450' },
  { label: 'Jackson', value: '451' },
  { label: 'Jacksonville', value: '452' },
  { label: 'Jamestown', value: '453' },
  { label: 'Jamesville', value: '454' },
  { label: 'Jefferson', value: '455' },
  { label: 'Jonesville', value: '456' },
  { label: 'Kannapolis', value: '457' },
  { label: 'Kelford', value: '458' },
  { label: 'Kenansville', value: '459' },
  { label: 'Kenly', value: '460' },
  { label: 'Kernersville', value: '461' },
  { label: 'Kill devil hills', value: '462' },
  { label: 'King', value: '463' },
  { label: 'Kings mountain', value: '464' },
  { label: 'Kingstown', value: '465' },
  { label: 'Kinston', value: '466' },
  { label: 'Kittrell', value: '467' },
  { label: 'Kitty hawk', value: '468' },
  { label: 'Knightdale', value: '469' },
  { label: 'Kure beach', value: '470' },
  { label: 'La grange', value: '471' },
  { label: 'Lake lure', value: '472' },
  { label: 'Lake park', value: '473' },
  { label: 'Lake santeetlah', value: '474' },
  { label: 'Lake waccamaw', value: '475' },
  { label: 'Landis', value: '476' },
  { label: 'Lansing', value: '477' },
  { label: 'Lasker', value: '478' },
  { label: 'Lattimore', value: '479' },
  { label: 'Laurel park', value: '480' },
  { label: 'Laurinburg', value: '481' },
  { label: 'Lawndale', value: '482' },
  { label: 'Leggett', value: '483' },
  { label: 'Leland', value: '484' },
  { label: 'Lenoir', value: '485' },
  { label: 'Lewiston woodville', value: '486' },
  { label: 'Lewisville', value: '487' },
  { label: 'Lexington', value: '488' },
  { label: 'Liberty', value: '489' },
  { label: 'Lilesville', value: '490' },
  { label: 'Lillington', value: '491' },
  { label: 'Lincolnton', value: '492' },
  { label: 'Linden', value: '493' },
  { label: 'Littleton', value: '494' },
  { label: 'Locust', value: '495' },
  { label: 'Long view', value: '496' },
  { label: 'Louisburg', value: '497' },
  { label: 'Love valley', value: '498' },
  { label: 'Lowell', value: '499' },
  { label: 'Lucama', value: '500' },
  { label: 'Lumber bridge', value: '501' },
  { label: 'Lumberton', value: '502' },
  { label: 'Macclesfield', value: '503' },
  { label: 'Macon', value: '504' },
  { label: 'Madison', value: '505' },
  { label: 'Maggie valley', value: '506' },
  { label: 'Magnolia', value: '507' },
  { label: 'Maiden', value: '508' },
  { label: 'Manteo', value: '509' },
  { label: 'Marietta', value: '510' },
  { label: 'Marion', value: '511' },
  { label: 'Mars hill', value: '512' },
  { label: 'Marshall', value: '513' },
  { label: 'Marshville', value: '514' },
  { label: 'Marvin', value: '515' },
  { label: 'Matthews', value: '516' },
  { label: 'Maxton', value: '517' },
  { label: 'Mayodan', value: '518' },
  { label: 'Maysville', value: '519' },
  { label: 'Mcadenville', value: '520' },
  { label: 'Mcdonald', value: '521' },
  { label: 'Mcfarlan', value: '522' },
  { label: 'Mebane', value: '523' },
  { label: 'Mesic', value: '524' },
  { label: 'Micro', value: '525' },
  { label: 'Middleburg', value: '526' },
  { label: 'Middlesex', value: '527' },
  { label: 'Midland', value: '528' },
  { label: 'Midway', value: '529' },
  { label: 'Mills river', value: '530' },
  { label: 'Milton', value: '531' },
  { label: 'Mineral springs', value: '532' },
  { label: 'Minnesott beach', value: '533' },
  { label: 'Mint hill', value: '534' },
  { label: 'Misenheimer', value: '535' },
  { label: 'Mocksville', value: '536' },
  { label: 'Momeyer', value: '537' },
  { label: 'Monroe', value: '538' },
  { label: 'Montreat', value: '539' },
  { label: 'Mooresboro', value: '540' },
  { label: 'Mooresville', value: '541' },
  { label: 'Morehead city', value: '542' },
  { label: 'Morganton', value: '543' },
  { label: 'Morrisville', value: '544' },
  { label: 'Morven', value: '545' },
  { label: 'Mount airy', value: '546' },
  { label: 'Mount gilead', value: '547' },
  { label: 'Mount holly', value: '548' },
  { label: 'Mount olive', value: '549' },
  { label: 'Mount pleasant', value: '550' },
];

const countyData = [
  { label: 'Pitt', value: '0' },
  { label: 'Pasquotank', value: '1' },
  { label: 'Lincoln', value: '2' },
  { label: 'Mecklenburg', value: '3' },
  { label: 'Moore', value: '4' },
  { label: 'Bladen', value: '5' },
  { label: 'Union', value: '6' },
  { label: 'Montgomery', value: '7' },
  { label: 'Person', value: '8' },
  { label: 'Cabarrus', value: '9' },
  { label: 'Ashe', value: '10' },
  { label: 'Cleveland', value: '11' },
  { label: 'Richmond', value: '12' },
  { label: 'Iredell', value: '13' },
  { label: 'Robeson', value: '14' },
  { label: 'Gaston', value: '15' },
  { label: 'Perquimans', value: '16' },
  { label: 'Vance', value: '17' },
  { label: 'Clay', value: '18' },
  { label: 'Alleghany', value: '19' },
  { label: 'Pamlico', value: '20' },
  { label: 'Duplin', value: '21' },
  { label: 'Pender', value: '22' },
  { label: 'Buncombe', value: '23' },
  { label: 'Alexander', value: '24' },
  { label: 'Sampson', value: '25' },
  { label: 'Rockingham', value: '26' },
  { label: 'Hyde', value: '27' },
  { label: 'Bertie', value: '28' },
  { label: 'Rutherford', value: '29' },
  { label: 'Brunswick', value: '30' },
  { label: 'Martin', value: '31' },
  { label: 'Mitchell', value: '32' },
  { label: 'Greene', value: '33' },
  { label: 'Davidson', value: '34' },
  { label: 'Wake', value: '35' },
  { label: 'Harnett', value: '36' },
  { label: 'Chowan', value: '37' },
  { label: 'Randolph', value: '38' },
  { label: 'Warren', value: '39' },
  { label: 'Stanly', value: '40' },
  { label: 'Madison', value: '41' },
  { label: 'Onslow', value: '42' },
  { label: 'Swain', value: '43' },
  { label: 'Nash', value: '44' },
  { label: 'Macon', value: '45' },
  { label: 'Davie', value: '46' },
  { label: 'Cherokee', value: '47' },
  { label: 'Lee', value: '48' },
  { label: 'Alamance', value: '49' },
  { label: 'Henderson', value: '50' },
  { label: 'Durham', value: '51' },
  { label: 'Burke', value: '52' },
  { label: 'Jackson', value: '53' },
  { label: 'Granville', value: '54' },
  { label: 'Hoke', value: '55' },
  { label: 'Wilson', value: '56' },
  { label: 'Caldwell', value: '57' },
  { label: 'Avery', value: '58' },
  { label: 'Surry', value: '59' },
  { label: 'New hanover', value: '60' },
  { label: 'Currituck', value: '61' },
  { label: 'Catawba', value: '62' },
  { label: 'Scotland', value: '63' },
  { label: 'Watauga', value: '64' },
  { label: 'Northampton', value: '65' },
  { label: 'Edgecombe', value: '66' },
  { label: 'Johnston', value: '67' },
  { label: 'Rowan', value: '68' },
  { label: 'Caswell', value: '69' },
  { label: 'Carteret', value: '70' },
  { label: 'Craven', value: '71' },
  { label: 'Washington', value: '72' },
  { label: 'Graham', value: '73' },
  { label: 'Transylvania', value: '74' },
  { label: 'Columbus', value: '75' },
  { label: 'Stokes', value: '76' },
  { label: 'Beaufort', value: '77' },
  { label: 'Camden', value: '78' },
  { label: 'Guilford', value: '79' },
  { label: 'Hertford', value: '80' },
  { label: 'Haywood', value: '81' },
  { label: 'Mcdowell', value: '82' },
  { label: 'Jones', value: '83' },
  { label: 'Wayne', value: '84' },
  { label: 'Chatham', value: '85' },
  { label: 'Forsyth', value: '86' },
  { label: 'Franklin', value: '87' },
  { label: 'Lenoir', value: '88' },
  { label: 'Yadkin', value: '89' },
  { label: 'Cumberland', value: '90' },
  { label: 'Tyrrell', value: '91' },
  { label: 'Polk', value: '92' },
  { label: 'Anson', value: '93' },
  { label: 'Halifax', value: '94' },
  { label: 'Gates', value: '95' },
  { label: 'Orange', value: '96' },
  { label: 'Yancey', value: '97' },
  { label: 'Dare', value: '98' },
  { label: 'Wilkes', value: '99' },
];

let divisionData = null;
function updateDivDropdown(value) {
  switch (value) {
    case '1':
      divisionData = cityData;
    case '2':
      divisionData = countyData;
  }
}

export default function Location({ navigation }) {
  const [value, setValue] = useState(null);
  const [isFocus, setIsFocus] = useState(false);

  return (
    < View >
      <Text>Where do you live?</Text>
      <View style={styles.container}>
        <Dropdown
          style={[styles.dropdown, isFocus && { borderColor: 'blue' }]}
          placeholderStyle={styles.placeholderStyle}
          selectedTextStyle={styles.selectedTextStyle}
          inputSearchStyle={styles.inputSearchStyle}
          data={divOptsData}
          maxHeight={300}
          labelField="label"
          valueField="value"
          // placeholder={!isFocus ? 'Select item' : '...'}
          searchPlaceholder="Search..."
          value={value}
          onFocus={() => setIsFocus(true)}
          onBlur={() => setIsFocus(false)}
          onChange={item => {
            setValue(item.value);
            setIsFocus(false);
            updateDivDropdown(item.value);
          }}
        />
      </View>
      {divisionData !== null ? <View style={styles.container}>
        <Dropdown
          style={[styles.dropdown, isFocus && { borderColor: 'blue' }]}
          placeholderStyle={styles.placeholderStyle}
          selectedTextStyle={styles.selectedTextStyle}
          inputSearchStyle={styles.inputSearchStyle}
          data={divisionData}
          maxHeight={300}
          labelField="label"
          valueField="value"
          placeholder={!isFocus ? 'Select item' : '...'}
          search
          searchPlaceholder="Search..."
          value={value}
          onFocus={() => setIsFocus(true)}
          onBlur={() => setIsFocus(false)}
          onChange={item => {
            setValue(item.value);
            setIsFocus(false);
            updateDivDropdown(item.value);
          }}
        />
      </View> : <View></View>}
      <Button
        title="Go to info"
        onPress={() => navigation.navigate("Info")}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    padding: 16,
  },
  dropdown: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});