import React, { useState } from "react";
import { StyleSheet, Button, View, Text } from "react-native";
import { Dropdown } from 'react-native-element-dropdown';
// import AntDesign from '@expo/vector-icons/AntDesign';

export default function Location({ navigation }) {
  const [divOptValue, setDivOptValue] = useState(null);
  const [divOptIsFocus, setDivOptIsFocus] = useState(false);
  const [cityValue, setCityValue] = useState(null);
  const [cityIsFocus, setCityIsFocus] = useState(false);
  const [countyValue, setCountyValue] = useState(null);
  const [countyIsFocus, setCountyIsFocus] = useState(false);

  return (
    < View >
      <View style={styles.container}>
        <Dropdown
          style={[styles.dropdown, divOptIsFocus && { borderColor: 'blue' }]}
          placeholderStyle={styles.placeholderStyle}
          selectedTextStyle={styles.selectedTextStyle}
          inputSearchStyle={styles.inputSearchStyle}
          data={divOptData}
          maxHeight={300}
          labelField="label"
          valueField="value"
          placeholder={!divOptIsFocus ? "Select city or county" : "..."}
          value={divOptValue}
          onFocus={() => setDivOptIsFocus(true)}
          onBlur={() => setDivOptIsFocus(false)}
          onChange={item => {
            setDivOptValue(item.value);
            setDivOptIsFocus(false);
          }}
        />
      </View>
      {divOptValue === null ? <View></View>
      :<View style={styles.container}>
        {divOptValue === '1' ?
          <Dropdown
            style={[styles.dropdown, cityIsFocus && { borderColor: 'blue' }]}
            placeholderStyle={styles.placeholderStyle}
            selectedTextStyle={styles.selectedTextStyle}
            inputSearchStyle={styles.inputSearchStyle}
            data={cityData}
            maxHeight={300}
            labelField="label"
            valueField="value"
            placeholder={!cityIsFocus ? 'Select city' : '...'}
            search
            searchPlaceholder="Search..."
            value={cityValue}
            onFocus={() => setCityIsFocus(true)}
            onBlur={() => setCityIsFocus(false)}
            onChange={item => {
              setCityValue(item.value);
              setCityIsFocus(false);
            }}
          /> :
          <Dropdown
            style={[styles.dropdown, countyIsFocus && { borderColor: 'blue' }]}
            placeholderStyle={styles.placeholderStyle}
            selectedTextStyle={styles.selectedTextStyle}
            inputSearchStyle={styles.inputSearchStyle}
            data={countyData}
            maxHeight={300}
            labelField="label"
            valueField="value"
            placeholder={!countyIsFocus ? 'Select county' : '...'}
            search
            searchPlaceholder="Search..."
            value={countyValue}
            onFocus={() => setCountyIsFocus(true)}
            onBlur={() => setCountyIsFocus(false)}
            onChange={item => {
              setCountyValue(item.value);
              setCountyIsFocus(false);
            }}
          />
        }
      </View>}
      <Button
        title="Get Recycling Laws"
        onPress={() => navigation.navigate("Info")}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    padding: 16,
  },
  dropdown: {
    height: 50,
    borderColor: 'gray',
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 22,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 14,
  },
  placeholderStyle: {
    fontSize: 16,
  },
  selectedTextStyle: {
    fontSize: 16,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
});

const divOptData = [
  { label: 'City', value: '1' },
  { label: 'County', value: '2' },
];

const cityData = [
  { label: 'Aberdeen', value: '0' },
  { label: 'Ahoskie', value: '1' },
  { label: 'Alamance', value: '2' },
  { label: 'Albemarle', value: '3' },
  { label: 'Alliance', value: '4' },
  { label: 'Andrews', value: '5' },
  { label: 'Angier', value: '6' },
  { label: 'Ansonville', value: '7' },
  { label: 'Apex', value: '8' },
  { label: 'Arapahoe', value: '9' },
  { label: 'Archdale', value: '10' },
  { label: 'Archer Lodge', value: '11' },
  { label: 'Asheboro', value: '12' },
  { label: 'Asheville', value: '13' },
  { label: 'Askewville', value: '14' },
  { label: 'Atkinson', value: '15' },
  { label: 'Atlantic Beach', value: '16' },
  { label: 'Aulander', value: '17' },
  { label: 'Aurora', value: '18' },
  { label: 'Autryville', value: '19' },
  { label: 'Ayden', value: '20' },
  { label: 'Badin', value: '21' },
  { label: 'Bailey', value: '22' },
  { label: 'Bakersville', value: '23' },
  { label: 'Bald Head Island', value: '24' },
  { label: 'Banner Elk', value: '25' },
  { label: 'Bath', value: '26' },
  { label: 'Bayboro', value: '27' },
  { label: 'Bear Grass', value: '28' },
  { label: 'Beaufort', value: '29' },
  { label: 'Beech Mountain', value: '30' },
  { label: 'Belhaven', value: '31' },
  { label: 'Belmont', value: '32' },
  { label: 'Belville', value: '33' },
  { label: 'Belwood', value: '34' },
  { label: 'Benson', value: '35' },
  { label: 'Bermuda Run', value: '36' },
  { label: 'Bessemer City', value: '37' },
  { label: 'Bethania', value: '38' },
  { label: 'Bethel', value: '39' },
  { label: 'Beulaville', value: '40' },
  { label: 'Biltmore Forest', value: '41' },
  { label: 'Biscoe', value: '42' },
  { label: 'Black Creek', value: '43' },
  { label: 'Black Mountain', value: '44' },
  { label: 'Bladenboro', value: '45' },
  { label: 'Blowing Rock', value: '46' },
  { label: 'Boardman', value: '47' },
  { label: 'Bogue', value: '48' },
  { label: 'Boiling Spring Lakes', value: '49' },
  { label: 'Boiling Springs', value: '50' },
  { label: 'Bolivia', value: '51' },
  { label: 'Bolton', value: '52' },
  { label: 'Boone', value: '53' },
  { label: 'Boonville', value: '54' },
  { label: 'Bostic', value: '55' },
  { label: 'Brevard', value: '56' },
  { label: 'Bridgeton', value: '57' },
  { label: 'Broadway', value: '58' },
  { label: 'Brookford', value: '59' },
  { label: 'Brunswick', value: '60' },
  { label: 'Bryson City', value: '61' },
  { label: 'Bunn', value: '62' },
  { label: 'Burgaw', value: '63' },
  { label: 'Burlington', value: '64' },
  { label: 'Burnsville', value: '65' },
  { label: 'Butner', value: '66' },
  { label: 'Cajahs Mountain', value: '67' },
  { label: 'Calabash', value: '68' },
  { label: 'Calypso', value: '69' },
  { label: 'Cameron', value: '70' },
  { label: 'Candor', value: '71' },
  { label: 'Canton', value: '72' },
  { label: 'Cape Carteret', value: '73' },
  { label: 'Carolina Beach', value: '74' },
  { label: 'Carolina Shores', value: '75' },
  { label: 'Carrboro', value: '76' },
  { label: 'Carthage', value: '77' },
  { label: 'Cary', value: '78' },
  { label: 'Casar', value: '79' },
  { label: 'Castalia', value: '80' },
  { label: 'Caswell Beach', value: '81' },
  { label: 'Catawba', value: '82' },
  { label: 'Cedar Point', value: '83' },
  { label: 'Cedar Rock', value: '84' },
  { label: 'Cerro Gordo', value: '85' },
  { label: 'Chadbourn', value: '86' },
  { label: 'Chapel Hill', value: '87' },
  { label: 'Charlotte', value: '88' },
  { label: 'Cherryville', value: '89' },
  { label: 'Chimney Rock', value: '90' },
  { label: 'China Grove', value: '91' },
  { label: 'Chocowinity', value: '92' },
  { label: 'Claremont', value: '93' },
  { label: 'Clarkton', value: '94' },
  { label: 'Clayton', value: '95' },
  { label: 'Clemmons', value: '96' },
  { label: 'Cleveland', value: '97' },
  { label: 'Clinton', value: '98' },
  { label: 'Clyde', value: '99' },
  { label: 'Coats', value: '100' },
  { label: 'Cofield', value: '101' },
  { label: 'Colerain', value: '102' },
  { label: 'Columbia', value: '103' },
  { label: 'Columbus', value: '104' },
  { label: 'Como', value: '105' },
  { label: 'Concord', value: '106' },
  { label: 'Conetoe', value: '107' },
  { label: 'Connelly Springs', value: '108' },
  { label: 'Conover', value: '109' },
  { label: 'Conway', value: '110' },
  { label: 'Cooleemee', value: '111' },
  { label: 'Cornelius', value: '112' },
  { label: 'Cove City', value: '113' },
  { label: 'Cramerton', value: '114' },
  { label: 'Creedmoor', value: '115' },
  { label: 'Creswell', value: '116' },
  { label: 'Crossnore', value: '117' },
  { label: 'Dallas', value: '118' },
  { label: 'Danbury', value: '119' },
  { label: 'Davidson', value: '120' },
  { label: 'Denton', value: '121' },
  { label: 'Dillsboro', value: '122' },
  { label: 'Dobbins Heights', value: '123' },
  { label: 'Dobson', value: '124' },
  { label: 'Dortches', value: '125' },
  { label: 'Dover', value: '126' },
  { label: 'Drexel', value: '127' },
  { label: 'Dublin', value: '128' },
  { label: 'Duck', value: '129' },
  { label: 'Dunn', value: '130' },
  { label: 'Durham', value: '131' },
  { label: 'Earl', value: '132' },
  { label: 'East Arcadia', value: '133' },
  { label: 'East Bend', value: '134' },
  { label: 'East Spencer', value: '135' },
  { label: 'Eastover', value: '136' },
  { label: 'Eden', value: '137' },
  { label: 'Edenton', value: '138' },
  { label: 'Elizabeth City', value: '139' },
  { label: 'Elizabethtown', value: '140' },
  { label: 'Elk Park', value: '141' },
  { label: 'Elkin', value: '142' },
  { label: 'Ellenboro', value: '143' },
  { label: 'Ellerbe', value: '144' },
  { label: 'Elm City', value: '145' },
  { label: 'Elon', value: '146' },
  { label: 'Emerald Isle', value: '147' },
  { label: 'Enfield', value: '148' },
  { label: 'Erwin', value: '149' },
  { label: 'Eureka', value: '150' },
  { label: 'Everetts', value: '151' },
  { label: 'Fair Bluff', value: '152' },
  { label: 'Fairmont', value: '153' },
  { label: 'Fairview', value: '154' },
  { label: 'Faison', value: '155' },
  { label: 'Faith', value: '156' },
  { label: 'Falcon', value: '157' },
  { label: 'Falkland', value: '158' },
  { label: 'Fallston', value: '159' },
  { label: 'Farmville', value: '160' },
  { label: 'Fayetteville', value: '161' },
  { label: 'Flat Rock', value: '162' },
  { label: 'Fletcher', value: '163' },
  { label: 'Fontana Dam', value: '164' },
  { label: 'Forest City', value: '165' },
  { label: 'Forest Hills', value: '166' },
  { label: 'Fountain', value: '167' },
  { label: 'Four Oaks', value: '168' },
  { label: 'Foxfire Village', value: '169' },
  { label: 'Franklin', value: '170' },
  { label: 'Franklinton', value: '171' },
  { label: 'Franklinville', value: '172' },
  { label: 'Fremont', value: '173' },
  { label: 'Fuquay-varina', value: '174' },
  { label: 'Gamewell', value: '175' },
  { label: 'Garland', value: '176' },
  { label: 'Garner', value: '177' },
  { label: 'Garysburg', value: '178' },
  { label: 'Gaston', value: '179' },
  { label: 'Gastonia', value: '180' },
  { label: 'Gatesville', value: '181' },
  { label: 'Gibson', value: '182' },
  { label: 'Gibsonville', value: '183' },
  { label: 'Glen Alpine', value: '184' },
  { label: 'Godwin', value: '185' },
  { label: 'Goldsboro', value: '186' },
  { label: 'Goldston', value: '187' },
  { label: 'Graham', value: '188' },
  { label: 'Grandfather Village', value: '189' },
  { label: 'Granite Falls', value: '190' },
  { label: 'Granite Quarry', value: '191' },
  { label: 'Grantsboro', value: '192' },
  { label: 'Green Level', value: '193' },
  { label: 'Greenevers', value: '194' },
  { label: 'Greensboro', value: '195' },
  { label: 'Greenville', value: '196' },
  { label: 'Grifton', value: '197' },
  { label: 'Grimesland', value: '198' },
  { label: 'Grover', value: '199' },
  { label: 'Halifax', value: '200' },
  { label: 'Hamilton', value: '201' },
  { label: 'Hamlet', value: '202' },
  { label: 'Harmony', value: '203' },
  { label: 'Harrells', value: '204' },
  { label: 'Harrellsville', value: '205' },
  { label: 'Harrisburg', value: '206' },
  { label: 'Hassell', value: '207' },
  { label: 'Havelock', value: '208' },
  { label: 'Haw River', value: '209' },
  { label: 'Hayesville', value: '210' },
  { label: 'Hemby Bridge', value: '211' },
  { label: 'Henderson', value: '212' },
  { label: 'Hendersonville', value: '213' },
  { label: 'Hertford', value: '214' },
  { label: 'Hickory', value: '215' },
  { label: 'High Point', value: '216' },
  { label: 'High Shoals', value: '217' },
  { label: 'Highlands', value: '218' },
  { label: 'Hildebran', value: '219' },
  { label: 'Hillsborough', value: '220' },
  { label: 'Hobgood', value: '221' },
  { label: 'Murfreesboro', value: '222' },
  { label: 'Murphy', value: '223' },
  { label: 'Nags Head', value: '224' },
  { label: 'Nashville', value: '225' },
  { label: 'Navassa', value: '226' },
  { label: 'New Bern', value: '227' },
  { label: 'New London', value: '228' },
  { label: 'Newland', value: '229' },
  { label: 'Newport', value: '230' },
  { label: 'Newton', value: '231' },
  { label: 'Newton Grove', value: '232' },
  { label: 'Norlina', value: '233' },
  { label: 'Norman', value: '234' },
  { label: 'North Topsail Beach', value: '235' },
  { label: 'North Wilkesboro', value: '236' },
  { label: 'Northwest', value: '237' },
  { label: 'Norwood', value: '238' },
  { label: 'Oak City', value: '239' },
  { label: 'Oak Island', value: '240' },
  { label: 'Oak Ridge', value: '241' },
  { label: 'Oakboro', value: '242' },
  { label: 'Ocean Isle Beach', value: '243' },
  { label: 'Old Fort', value: '244' },
  { label: 'Oriental', value: '245' },
  { label: 'Orrum', value: '246' },
  { label: 'Ossipee', value: '247' },
  { label: 'Oxford', value: '248' },
  { label: 'Pantego', value: '249' },
  { label: 'Parkton', value: '250' },
  { label: 'Parmele', value: '251' },
  { label: 'Patterson Springs', value: '252' },
  { label: 'Peachland', value: '253' },
  { label: 'Peletier', value: '254' },
  { label: 'Pembroke', value: '255' },
  { label: 'Pikeville', value: '256' },
  { label: 'Pilot Mountain', value: '257' },
  { label: 'Pine Knoll Shores', value: '258' },
  { label: 'Pine Level', value: '259' },
  { label: 'Pinebluff', value: '260' },
  { label: 'Pinehurst', value: '261' },
  { label: 'Pinetops', value: '262' },
  { label: 'Pineville', value: '263' },
  { label: 'Pink Hill', value: '264' },
  { label: 'Pittsboro', value: '265' },
  { label: 'Pleasant Garden', value: '266' },
  { label: 'Plymouth', value: '267' },
  { label: 'Polkton', value: '268' },
  { label: 'Polkville', value: '269' },
  { label: 'Pollocksville', value: '270' },
  { label: 'Powellsville', value: '271' },
  { label: 'Princeton', value: '272' },
  { label: 'Princeville', value: '273' },
  { label: 'Proctorville', value: '274' },
  { label: 'Raeford', value: '275' },
  { label: 'Raleigh', value: '276' },
  { label: 'Ramseur', value: '277' },
  { label: 'Randleman', value: '278' },
  { label: 'Ranlo', value: '279' },
  { label: 'Raynham', value: '280' },
  { label: 'Red Cross', value: '281' },
  { label: 'Red Oak', value: '282' },
  { label: 'Red Springs', value: '283' },
  { label: 'Reidsville', value: '284' },
  { label: 'Rennert', value: '285' },
  { label: 'Rhodhiss', value: '286' },
  { label: 'Rich Square', value: '287' },
  { label: 'Richfield', value: '288' },
  { label: 'Richlands', value: '289' },
  { label: 'River Bend', value: '290' },
  { label: 'Roanoke Rapids', value: '291' },
  { label: 'Robbins', value: '292' },
  { label: 'Robbinsville', value: '293' },
  { label: 'Robersonville', value: '294' },
  { label: 'Rockingham', value: '295' },
  { label: 'Rockwell', value: '296' },
  { label: 'Rocky Mount', value: '297' },
  { label: 'Rolesville', value: '298' },
  { label: 'Ronda', value: '299' },
  { label: 'Roper', value: '300' },
  { label: 'Rose Hill', value: '301' },
  { label: 'Roseboro', value: '302' },
  { label: 'Rosman', value: '303' },
  { label: 'Rowland', value: '304' },
  { label: 'Roxboro', value: '305' },
  { label: 'Roxobel', value: '306' },
  { label: 'Rural Hall', value: '307' },
  { label: 'Ruth', value: '308' },
  { label: 'Rutherford College', value: '309' },
  { label: 'Rutherfordton', value: '310' },
  { label: 'Saint Helena', value: '311' },
  { label: 'Saint James', value: '312' },
  { label: 'Saint Pauls', value: '313' },
  { label: 'Salemburg', value: '314' },
  { label: 'Salisbury', value: '315' },
  { label: 'Saluda', value: '316' },
  { label: 'Sandy Creek', value: '317' },
  { label: 'Sandyfield', value: '318' },
  { label: 'Sanford', value: '319' },
  { label: 'Saratoga', value: '320' },
  { label: 'Sawmills', value: '321' },
  { label: 'Scotland Neck', value: '322' },
  { label: 'Seaboard', value: '323' },
  { label: 'Seagrove', value: '324' },
  { label: 'Sedalia', value: '325' },
  { label: 'Selma', value: '326' },
  { label: 'Seven Devils', value: '327' },
  { label: 'Seven Springs', value: '328' },
  { label: 'Severn', value: '329' },
  { label: 'Shallotte', value: '330' },
  { label: 'Sharpsburg', value: '331' },
  { label: 'Shelby', value: '332' },
  { label: 'Siler City', value: '333' },
  { label: 'Simpson', value: '334' },
  { label: 'Sims', value: '335' },
  { label: 'Smithfield', value: '336' },
  { label: 'Snow Hill', value: '337' },
  { label: 'Southern Pines', value: '338' },
  { label: 'Southern Shores', value: '339' },
  { label: 'Southport', value: '340' },
  { label: 'Sparta', value: '341' },
  { label: 'Speed', value: '342' },
  { label: 'Spencer', value: '343' },
  { label: 'Spencer Mountain', value: '344' },
  { label: 'Spindale', value: '345' },
  { label: 'Spring Hope', value: '346' },
  { label: 'Spring Lake', value: '347' },
  { label: 'Spruce Pine', value: '348' },
  { label: 'Staley', value: '349' },
  { label: 'Stallings', value: '350' },
  { label: 'Stanfield', value: '351' },
  { label: 'Stanley', value: '352' },
  { label: 'Stantonsburg', value: '353' },
  { label: 'Star', value: '354' },
  { label: 'Statesville', value: '355' },
  { label: 'Stedman', value: '356' },
  { label: 'Stem', value: '357' },
  { label: 'Stokesdale', value: '358' },
  { label: 'Stoneville', value: '359' },
  { label: 'Stonewall', value: '360' },
  { label: 'Stovall', value: '361' },
  { label: 'Sugar Mountain', value: '362' },
  { label: 'Summerfield', value: '363' },
  { label: 'Sunset Beach', value: '364' },
  { label: 'Surf City', value: '365' },
  { label: 'Swansboro', value: '366' },
  { label: 'Swepsonville', value: '367' },
  { label: 'Sylva', value: '368' },
  { label: 'Tabor City', value: '369' },
  { label: 'Tar Heel', value: '370' },
  { label: 'Tarboro', value: '371' },
  { label: 'Taylorsville', value: '372' },
  { label: 'Taylortown', value: '373' },
  { label: 'Teachey', value: '374' },
  { label: 'Thomasville', value: '375' },
  { label: 'Tobaccoville', value: '376' },
  { label: 'Topsail Beach', value: '377' },
  { label: 'Trent Woods', value: '378' },
  { label: 'Trenton', value: '379' },
  { label: 'Trinity', value: '380' },
  { label: 'Troutman', value: '381' },
  { label: 'Troy', value: '382' },
  { label: 'Tryon', value: '383' },
  { label: 'Turkey', value: '384' },
  { label: 'Unionville', value: '385' },
  { label: 'Valdese', value: '386' },
  { label: 'Vanceboro', value: '387' },
  { label: 'Vandemere', value: '388' },
  { label: 'Varnamtown', value: '389' },
  { label: 'Vass', value: '390' },
  { label: 'Waco', value: '391' },
  { label: 'Wade', value: '392' },
  { label: 'Wadesboro', value: '393' },
  { label: 'Wagram', value: '394' },
  { label: 'Wake Forest', value: '395' },
  { label: 'Walkertown', value: '396' },
  { label: 'Wallace', value: '397' },
  { label: 'Wallburg', value: '398' },
  { label: 'Walnut Cove', value: '399' },
  { label: 'Walnut Creek', value: '400' },
  { label: 'Walstonburg', value: '401' },
  { label: 'Warrenton', value: '402' },
  { label: 'Warsaw', value: '403' },
  { label: 'Washington', value: '404' },
  { label: 'Washington Park', value: '405' },
  { label: 'Watha', value: '406' },
  { label: 'Waxhaw', value: '407' },
  { label: 'Waynesville', value: '408' },
  { label: 'Weaverville', value: '409' },
  { label: 'Webster', value: '410' },
  { label: 'Weddington', value: '411' },
  { label: 'Weldon', value: '412' },
  { label: 'Wendell', value: '413' },
  { label: 'Wentworth', value: '414' },
  { label: 'Wesley Chapel', value: '415' },
  { label: 'West Jefferson', value: '416' },
  { label: 'Whispering Pines', value: '417' },
  { label: 'Whitakers', value: '418' },
  { label: 'White Lake', value: '419' },
  { label: 'Whiteville', value: '420' },
  { label: 'Whitsett', value: '421' },
  { label: 'Wilkesboro', value: '422' },
  { label: 'Williamston', value: '423' },
  { label: 'Wilmington', value: '424' },
  { label: 'Wilson', value: '425' },
  { label: 'Wilsons Mills', value: '426' },
  { label: 'Windsor', value: '427' },
  { label: 'Winfall', value: '428' },
  { label: 'Wingate', value: '429' },
  { label: 'Winston-salem', value: '430' },
  { label: 'Winterville', value: '431' },
  { label: 'Winton', value: '432' },
  { label: 'Woodfin', value: '433' },
  { label: 'Woodland', value: '434' },
  { label: 'Wrightsville Beach', value: '435' },
  { label: 'Yadkinville', value: '436' },
  { label: 'Yanceyville', value: '437' },
  { label: 'Youngsville', value: '438' },
  { label: 'Zebulon', value: '439' },
  { label: 'Hoffman', value: '440' },
  { label: 'Holden Beach', value: '441' },
  { label: 'Holly Ridge', value: '442' },
  { label: 'Holly Springs', value: '443' },
  { label: 'Hookerton', value: '444' },
  { label: 'Hope Mills', value: '445' },
  { label: 'Hot Springs', value: '446' },
  { label: 'Hudson', value: '447' },
  { label: 'Huntersville', value: '448' },
  { label: 'Indian Beach', value: '449' },
  { label: 'Indian Trail', value: '450' },
  { label: 'Jackson', value: '451' },
  { label: 'Jacksonville', value: '452' },
  { label: 'Jamestown', value: '453' },
  { label: 'Jamesville', value: '454' },
  { label: 'Jefferson', value: '455' },
  { label: 'Jonesville', value: '456' },
  { label: 'Kannapolis', value: '457' },
  { label: 'Kelford', value: '458' },
  { label: 'Kenansville', value: '459' },
  { label: 'Kenly', value: '460' },
  { label: 'Kernersville', value: '461' },
  { label: 'Kill Devil Hills', value: '462' },
  { label: 'King', value: '463' },
  { label: 'Kings Mountain', value: '464' },
  { label: 'Kingstown', value: '465' },
  { label: 'Kinston', value: '466' },
  { label: 'Kittrell', value: '467' },
  { label: 'Kitty Hawk', value: '468' },
  { label: 'Knightdale', value: '469' },
  { label: 'Kure Beach', value: '470' },
  { label: 'La Grange', value: '471' },
  { label: 'Lake Lure', value: '472' },
  { label: 'Lake Park', value: '473' },
  { label: 'Lake Santeetlah', value: '474' },
  { label: 'Lake Waccamaw', value: '475' },
  { label: 'Landis', value: '476' },
  { label: 'Lansing', value: '477' },
  { label: 'Lasker', value: '478' },
  { label: 'Lattimore', value: '479' },
  { label: 'Laurel Park', value: '480' },
  { label: 'Laurinburg', value: '481' },
  { label: 'Lawndale', value: '482' },
  { label: 'Leggett', value: '483' },
  { label: 'Leland', value: '484' },
  { label: 'Lenoir', value: '485' },
  { label: 'Lewiston Woodville', value: '486' },
  { label: 'Lewisville', value: '487' },
  { label: 'Lexington', value: '488' },
  { label: 'Liberty', value: '489' },
  { label: 'Lilesville', value: '490' },
  { label: 'Lillington', value: '491' },
  { label: 'Lincolnton', value: '492' },
  { label: 'Linden', value: '493' },
  { label: 'Littleton', value: '494' },
  { label: 'Locust', value: '495' },
  { label: 'Long View', value: '496' },
  { label: 'Louisburg', value: '497' },
  { label: 'Love Valley', value: '498' },
  { label: 'Lowell', value: '499' },
  { label: 'Lucama', value: '500' },
  { label: 'Lumber Bridge', value: '501' },
  { label: 'Lumberton', value: '502' },
  { label: 'Macclesfield', value: '503' },
  { label: 'Macon', value: '504' },
  { label: 'Madison', value: '505' },
  { label: 'Maggie Valley', value: '506' },
  { label: 'Magnolia', value: '507' },
  { label: 'Maiden', value: '508' },
  { label: 'Manteo', value: '509' },
  { label: 'Marietta', value: '510' },
  { label: 'Marion', value: '511' },
  { label: 'Mars Hill', value: '512' },
  { label: 'Marshall', value: '513' },
  { label: 'Marshville', value: '514' },
  { label: 'Marvin', value: '515' },
  { label: 'Matthews', value: '516' },
  { label: 'Maxton', value: '517' },
  { label: 'Mayodan', value: '518' },
  { label: 'Maysville', value: '519' },
  { label: 'Mcadenville', value: '520' },
  { label: 'Mcdonald', value: '521' },
  { label: 'Mcfarlan', value: '522' },
  { label: 'Mebane', value: '523' },
  { label: 'Mesic', value: '524' },
  { label: 'Micro', value: '525' },
  { label: 'Middleburg', value: '526' },
  { label: 'Middlesex', value: '527' },
  { label: 'Midland', value: '528' },
  { label: 'Midway', value: '529' },
  { label: 'Mills River', value: '530' },
  { label: 'Milton', value: '531' },
  { label: 'Mineral Springs', value: '532' },
  { label: 'Minnesott Beach', value: '533' },
  { label: 'Mint Hill', value: '534' },
  { label: 'Misenheimer', value: '535' },
  { label: 'Mocksville', value: '536' },
  { label: 'Momeyer', value: '537' },
  { label: 'Monroe', value: '538' },
  { label: 'Montreat', value: '539' },
  { label: 'Mooresboro', value: '540' },
  { label: 'Mooresville', value: '541' },
  { label: 'Morehead City', value: '542' },
  { label: 'Morganton', value: '543' },
  { label: 'Morrisville', value: '544' },
  { label: 'Morven', value: '545' },
  { label: 'Mount Airy', value: '546' },
  { label: 'Mount Gilead', value: '547' },
  { label: 'Mount Holly', value: '548' },
  { label: 'Mount Olive', value: '549' },
  { label: 'Mount Pleasant', value: '550' },
];

const countyData = [
  { label: 'Alamance', value: '0' },
  { label: 'Alexander', value: '1' },
  { label: 'Alleghany', value: '2' },
  { label: 'Anson', value: '3' },
  { label: 'Ashe', value: '4' },
  { label: 'Avery', value: '5' },
  { label: 'Beaufort', value: '6' },
  { label: 'Bertie', value: '7' },
  { label: 'Bladen', value: '8' },
  { label: 'Brunswick', value: '9' },
  { label: 'Buncombe', value: '10' },
  { label: 'Burke', value: '11' },
  { label: 'Cabarrus', value: '12' },
  { label: 'Caldwell', value: '13' },
  { label: 'Camden', value: '14' },
  { label: 'Carteret', value: '15' },
  { label: 'Caswell', value: '16' },
  { label: 'Catawba', value: '17' },
  { label: 'Chatham', value: '18' },
  { label: 'Cherokee', value: '19' },
  { label: 'Chowan', value: '20' },
  { label: 'Clay', value: '21' },
  { label: 'Cleveland', value: '22' },
  { label: 'Columbus', value: '23' },
  { label: 'Craven', value: '24' },
  { label: 'Cumberland', value: '25' },
  { label: 'Currituck', value: '26' },
  { label: 'Dare', value: '27' },
  { label: 'Davidson', value: '28' },
  { label: 'Davie', value: '29' },
  { label: 'Duplin', value: '30' },
  { label: 'Durham', value: '31' },
  { label: 'Edgecombe', value: '32' },
  { label: 'Forsyth', value: '33' },
  { label: 'Franklin', value: '34' },
  { label: 'Gaston', value: '35' },
  { label: 'Gates', value: '36' },
  { label: 'Graham', value: '37' },
  { label: 'Granville', value: '38' },
  { label: 'Greene', value: '39' },
  { label: 'Guilford', value: '40' },
  { label: 'Halifax', value: '41' },
  { label: 'Harnett', value: '42' },
  { label: 'Haywood', value: '43' },
  { label: 'Henderson', value: '44' },
  { label: 'Hertford', value: '45' },
  { label: 'Hoke', value: '46' },
  { label: 'Hyde', value: '47' },
  { label: 'Iredell', value: '48' },
  { label: 'Jackson', value: '49' },
  { label: 'Johnston', value: '50' },
  { label: 'Jones', value: '51' },
  { label: 'Lee', value: '52' },
  { label: 'Lenoir', value: '53' },
  { label: 'Lincoln', value: '54' },
  { label: 'Macon', value: '55' },
  { label: 'Madison', value: '56' },
  { label: 'Martin', value: '57' },
  { label: 'Mcdowell', value: '58' },
  { label: 'Mecklenburg', value: '59' },
  { label: 'Mitchell', value: '60' },
  { label: 'Montgomery', value: '61' },
  { label: 'Moore', value: '62' },
  { label: 'Nash', value: '63' },
  { label: 'New hanover', value: '64' },
  { label: 'Northampton', value: '65' },
  { label: 'Onslow', value: '66' },
  { label: 'Orange', value: '67' },
  { label: 'Pamlico', value: '68' },
  { label: 'Pasquotank', value: '69' },
  { label: 'Pender', value: '70' },
  { label: 'Perquimans', value: '71' },
  { label: 'Person', value: '72' },
  { label: 'Pitt', value: '73' },
  { label: 'Polk', value: '74' },
  { label: 'Randolph', value: '75' },
  { label: 'Richmond', value: '76' },
  { label: 'Robeson', value: '77' },
  { label: 'Rockingham', value: '78' },
  { label: 'Rowan', value: '79' },
  { label: 'Rutherford', value: '80' },
  { label: 'Sampson', value: '81' },
  { label: 'Scotland', value: '82' },
  { label: 'Stanly', value: '83' },
  { label: 'Stokes', value: '84' },
  { label: 'Surry', value: '85' },
  { label: 'Swain', value: '86' },
  { label: 'Transylvania', value: '87' },
  { label: 'Tyrrell', value: '88' },
  { label: 'Union', value: '89' },
  { label: 'Vance', value: '90' },
  { label: 'Wake', value: '91' },
  { label: 'Warren', value: '92' },
  { label: 'Washington', value: '93' },
  { label: 'Watauga', value: '94' },
  { label: 'Wayne', value: '95' },
  { label: 'Wilkes', value: '96' },
  { label: 'Wilson', value: '97' },
  { label: 'Yadkin', value: '98' },
  { label: 'Yancey', value: '99' },
];